### ISSUE TITLE
Adding graphql support

### ISSUE THREAD

**Issue by realamirhe** [flawiddsouza/Restfox#1]
Thanks for maintaining this project :)
Is there any plan for adding graphql support?

Now non of the existing method works for achieving the same result as follows

```shell
curl --request POST \
  --url https://rickandmortyapi.com/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"# https://rickandmortyapi.com/graphql\nquery {\n\tcharacters {\n\t\tresults {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n}\n","variables":{"page":0}}'
```

**Comment by flawiddsouza** [comment]
Hey @realamirhe,

The same curl request can be accomplished with the JSON body:
![image](https://user-images.githubusercontent.com/10164500/188067698-62c73e45-6d34-4e5e-9499-e32b95a0b932.png)

Try importing this export: [Restfox_2022-09-02_GraphQL_Call_test.json.txt](https://github.com/flawiddsouza/Restfox/files/9475188/Restfox_2022-09-02_GraphQL_Call_test.json.txt) Remove the .txt extension from the end.

I'm definitely open to adding proper graphql support in the near future.

**Comment by realamirhe** [comment]
Thanks, 
It would be great if we can add see and edit JSON easily, but it is fine for now :)))

**Comment by flawiddsouza** [comment]
Hey @realamirhe, I went ahead and implemented graphql support.

Steps to use:
1. Goto https://restfox.dev and update to the latest version:
![image](https://user-images.githubusercontent.com/10164500/188219369-558e96c6-76c2-43cd-bf8d-bdd0c705b6c6.png)
2. Find the GraphQL option in Body:
![image](https://user-images.githubusercontent.com/10164500/188219796-95bb65fb-4271-457b-afa7-0666dd66957b.png)
3. GraphQL Request export for reference: [Restfox_2022-09-03.json.txt](https://github.com/flawiddsouza/Restfox/files/9480461/Restfox_2022-09-03.json.txt) Remove the .txt extension from the end to be able to import it.

Hope you find this useful 😄

**Comment by realamirhe** [comment]
That's amazing @flawiddsouza, I'm going to test it out
