### ISSUE TITLE
bulk edit headers

### ISSUE THREAD

**Issue by vcoris** [flawiddsouza/Restfox#101]
I think it would be nice to have the ability to bulk edit the header in json format.
I just had a request that contains a dozen headers....

**Comment by flawiddsouza** [comment]
Hi @vcoris, I'll definitely consider this since this is the 2nd time I've gotten this request. I'll close this issue as there's already one open at https://github.com/flawiddsouza/Restfox/issues/13. You can follow that to be notified when I implement it.
