### ISSUE TITLE
[Feature Request] - reading filesystem in plugin

### ISSUE THREAD

**Issue by khopland** [flawiddsouza/Restfox#102]
I would be great to be able to read text file from filesystem in plugins😄.

**Comment by flawiddsouza** [comment]
Hi @khopland, this is now implemented as of [v0.9.0](https://github.com/flawiddsouza/Restfox/releases/tag/v0.9.0).

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/80435284-95b2-4277-91a8-35614961d4a6)
