### ISSUE TITLE
I don’t understand the synchronization logic between the request parameter page and the address bar

### ISSUE THREAD

**Issue by mofazhe** [flawiddsouza/Restfox#104]
When I paste the URL, the request parameter page will automatically create the corresponding item, which is no problem. There is something wrong with the following scenario:
1. I unchecked the check box on the request parameters page, but there was no change in the address bar, and it did not take effect when I made the final request.
2. When modifying the key of request parameters, there is no change in the address bar. A new parameter is added in the final request.

I have used Postman, and I feel its logic is more reasonable. Changes to the address bar or request parameters are synchronized. However, Restfox feels that sometimes it is synchronized and sometimes not, which is a bit difficult to understand. I feel it is a bug.

![image](https://github.com/flawiddsouza/Restfox/assets/41715438/aebe6bee-b519-4844-8446-34493dfc2648)

**Comment by flawiddsouza** [comment]
This is definitely a bug. Will look into this.

**Comment by flawiddsouza** [comment]
This issue is resolved as of the latest commit.  Now query params will always stay in sync with each other.
