### ISSUE TITLE
OpenAPI Imports

### ISSUE THREAD

**Issue by scottj** [flawiddsouza/Restfox#11]
While it's great to be able to import Postman data, I would say that probably half of the things I'm typically importing into Postman are actually OpenAPI files. I would love to see OpenAPI import support in this tool so that I can say goodbye forever to Postman.

**Comment by mishushakov** [comment]
Restfox team, please take a look at insomnia-importers package: https://www.npmjs.com/package/insomnia-importers
They support converting various formats (OpenAPI included) into insomnia format, which is just JSON you can convert into Restfox format

**Comment by flawiddsouza** [comment]
@mishushakov Seems like the package is very buggy when used with vite and browser based environments. I just had to revert the commit sadly. It was working fine in dev mode but breaks completely in the prod mode. It also adds about +2 MB to the ui bundle size. PR at https://github.com/flawiddsouza/Restfox/pull/30.

**Comment by mishushakov** [comment]
Didn't know that, sorry. Could you run it using a serverless function?
Also, I'd love to connect with you to talk about a possible collaboration between Restfox and Step CI. Would you mind shooting me an email at mish at stepci.com

Thanks

**Comment by flawiddsouza** [comment]
@scottj OpenAPI import is now available:

![image](https://user-images.githubusercontent.com/10164500/204119478-39d292af-c5ec-464b-b8bc-1365e6367046.png)

**Comment by scottj** [comment]
This is amazing! Thanks @flawiddsouza!
