### ISSUE TITLE
How can I add query params in plugin

### ISSUE THREAD

**Issue by mofazhe** [flawiddsouza/Restfox#110]
I based on this request definition of parameters: 
![image](https://github.com/flawiddsouza/Restfox/assets/41715438/53a4eb63-6497-4333-aa15-1551ad808d08)

Here is my code of plugin: 
```js
function handleRequest() {
    // console.log(context.request.getBody())

    var timestamp=Date.now();
    console.log(timestamp)
    context.request.setEnvironmentVariable('timestamp', timestamp)
    var params=context.request.getQueryParams();
    console.log(params)
    params.push({"name":"time","value":"1232"});
    console.log(params)
    context.request.setQueryParams(params);
}

if('request' in context) {
    handleRequest()
}
```
But, here is the result: 
![image](https://github.com/flawiddsouza/Restfox/assets/41715438/e7c0d980-e9d7-42ae-b8f1-e4fda060b717)

Changes to environment variables in `handleRequest` also do not take effect in the request parameters, see the environment variable `timestamp` above.

**Comment by flawiddsouza** [comment]
> Changes to environment variables in handleRequest also do not take effect in the request parameters, see the environment variable timestamp above.

This now fixed.

This should work:
```
const queryParams = context.request.getQueryParams()
context.request.setQueryParams([...queryParams, { name: 'cat', value: '3' }])
```
Your code should work but looks like there's a limitation in the underlying library that I'm using for running plugins. I'll look into fixing that.

**Comment by flawiddsouza** [comment]
> Changes to environment variables in handleRequest also do not take effect in the request parameters, see the environment variable timestamp above.

This now fixed.

This should work:
```
const queryParams = context.request.getQueryParams()
context.request.setQueryParams([...queryParams, { name: 'cat', value: '3' }])
```

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/fb7bbef0-3b85-4dc7-b084-f04004322d26)

Your code should work but looks like there's a limitation in the underlying library that I'm using for running plugins. I'll look into fixing that.

**Comment by flawiddsouza** [comment]
> Changes to environment variables in handleRequest also do not take effect in the request parameters, see the environment variable timestamp above.

This is now fixed.

This should work:
```
const queryParams = context.request.getQueryParams()
context.request.setQueryParams([...queryParams, { name: 'cat', value: '3' }])
```

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/fb7bbef0-3b85-4dc7-b084-f04004322d26)

Your code should work but looks like there's a limitation in the underlying library that I'm using for running plugins. I'll look into fixing that.

**Comment by mofazhe** [comment]
> > Changes to environment variables in handleRequest also do not take effect in the request parameters, see the environment variable timestamp above.
>
> This is now fixed.

I will try it in next version.


> This should work:
> ```
> const queryParams = context.request.getQueryParams()
> context.request.setQueryParams([...queryParams, { name: 'cat', value: '3' }])
> ```

I tried the code and it worked fine.

> Your code should work but looks like there's a limitation in the underlying library that I'm using for running plugins. I'll look into fixing that.

That would be great.

**Comment by flawiddsouza** [comment]
Closing this for now, as there's a workaround. I'll try to fix the query params direct usage issue in the next release. A new version has been released. It has the fix for the environment variable issue you reported.
