### ISSUE TITLE
View  / persistence of plugins can get out of sync

### ISSUE THREAD

**Issue by ViToni** [flawiddsouza/Restfox#111]
It seems this issue can occur in multiple places (e.g. the folder view when moving requests), but it's easiest to reproduce with the "Plugins" dialog.

1. Open "Plugins" dialog
2. Click "Add Plugin".
3. Name: "GhostPlugin", Scope: "Current Workspace"
4. Save
5. => Plugin appears in "Workspace Plugins" section
6. Edit "GhostPlugin"
7. Change Scope to "All Workspaces"
8. Save
9. The plugin is gone (from the view) and does not appear in "Global Plugins" section
10. Quit Restfox
11. Start Restfox
12. Open "Plugins" dialog
13. "GhostPlugin" is shown in "Global Plugins" section

Tested with Restfox 0.9.1. on MacOS Sonoma 14.4.

**Comment by flawiddsouza** [comment]
This is definitely a bug. Most likely introduced after I implemented File Workspaces. Thanks for reporting this.

**Comment by ViToni** [comment]
> > It seems this issue can occur in multiple places (e.g. the folder view when moving requests)
>
> Can you expand more on this? This might be a different issue. I'm asking because there's no scope dropdown in Plugins for a request or a folder.

I' m pretty sure I had a (seemingly) similar issue when trying to organize my requests into folders. After restarting Restfox the folder structure looked differently... By "similar" I mean that there was a discrepancy between the view before and after restarting Restfox (my assumption was that view and persited data might diverge and there might be a general issue in the way UI changes are persisted).
But I couldn't recreate the steps to reproduce it. At least with 0.9.1 I don't see it happening again.
(If it ever occurs again I'll create a separate issue with the steps needed.)

**Comment by flawiddsouza** [comment]
> But I couldn't recreate the steps to reproduce it. At least with 0.9.1 I don't see it happening again.
(If it ever occurs again I'll create a separate issue with the steps needed.)

I'd be more than happy to fix this if I get the reproduction steps.

Will most likely push a fix for the plugins issue tomorrow. That's very reproducible. Rare bugs are very hard to catch in comparison.
