### ISSUE TITLE
Support secret environment values that aren't saved in version control

### ISSUE THREAD

**Issue by bkane-msft** [flawiddsouza/Restfox#114]
Hello! is there a way to save environment variables such as API keys so they don't end up in source control (i.e., the `_environments/<name>.json` file?

I'm worried I'll accidentally commit API keys.

**Comment by bkane-msft** [comment]
For inspiration, here's what Bruno does - https://docs.usebruno.com/secrets-management/overview . I'm not sure about other REST clients.

**Comment by flawiddsouza** [comment]
Hi @bkane-msft, now you can create a .env file in the root of your workspace directory and use the env variables in the environments like so:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/b8d28066-a3b2-4c97-9254-0dceacbeeecd)

Direct environment secrets will be coming in an upcoming release. Hope this will suffice for now. The version with this feature will be released tomorrow.

**Comment by flawiddsouza** [comment]
Hi @bkane-msft, now you can create a .env file in the root of your workspace directory and use the process.env variables in the environments like so:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/b8d28066-a3b2-4c97-9254-0dceacbeeecd)

Direct environment secrets will be coming in an upcoming release. Hope this will suffice for now. The version with this feature will be released tomorrow.

**Comment by bkane-msft** [comment]
That absolutely works for now. Thank you @flawiddsouza , I really appreciate the quick turnaround time!
