### ISSUE TITLE
Support for form-data

### ISSUE THREAD

**Issue by manueljeffin** [flawiddsouza/Restfox#12]
Have a use case to use form-data where I need to upload a file in the request as part of body. Going by the options in dropdown, looks like form-data is not supported. 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/8822750/197763727-f70b5a4c-2bc6-42d1-b559-4d6c6fb30863.png">

Could you please help

**Comment by flawiddsouza** [comment]
@manueljeffin This feature is now implemented and deployed to https://restfox.dev. Do check and let me know.

You'll have to click on reload on the update dialog to get the latest version of the application:
![image](https://user-images.githubusercontent.com/10164500/197813244-fb86785b-618b-4925-99be-790d9f8fc5a3.png)
