### ISSUE TITLE
Collection Settings

### ISSUE THREAD

**Issue by g-gibosky** [flawiddsouza/Restfox#121]
Would be great if there is a possibility to have settings for given collections, like show below on thunder client

![image](https://github.com/flawiddsouza/Restfox/assets/32047751/cd428a3e-e6ac-4588-95d2-285afef4cf3e)

One key element is the environment that is liked as shown below:
![image](https://github.com/flawiddsouza/Restfox/assets/32047751/37b61b63-58f1-4511-b070-a9529ee67e7d)

This type of config help a lot when the user have multiple stages and want to configure it based on that.

Thanks

**Comment by flawiddsouza** [comment]
A folder can already have it's own set of environments, plugins (scripts / tests) & properties (headers & auth):

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/15c3685b-b773-4172-9574-385ca0cac886)
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/0efb0244-d6c6-493c-bcae-63d48700b25b)
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/251a91ce-9e02-45a3-86f1-df9d6ca1d06e)

You can also have multiple environments for one workspace:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/e95caca3-faa2-4ce2-b907-39b9e2d5a5f1)
You can switch them here:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/9747415a-9262-4a9e-9588-9f85a6c1a63e)

Maybe it's not clear but the Environment is clickable in the navbar.

Let me know if you think something is missing.

**Comment by flawiddsouza** [comment]
Closing this as there's no reply. I'll reopen this if there's something missing.
