### ISSUE TITLE
There are some issues with pasting content into url and scripts

### ISSUE THREAD

**Issue by mofazhe** [flawiddsouza/Restfox#124]
I'm currently using 0.11.0

Here are the steps to reproduce: 

1. Create a new request
2. Paste the url, pre request script, post request script in order (actually normal hand speed is not fast)
3. Send the request and check the console
4. The console does not print the post request script.

If you are still confused, check out the video below: 
> The content of the post request script of the new request will be the next question I want to talk about.

https://github.com/flawiddsouza/Restfox/assets/41715438/63d4aea0-bd17-4117-9481-c41c8952ed91

----
There is another question here. I think it may be related to the above question because the steps to reproduce are similar.

1. Create a new request
2. Paste the url, then paste the pre request script or post request script
3. Create a new request and find that the content of the previous request will exist in the script.
4. When I close restfox and reopen it, I will find that the contents of the two request scripts are empty.

There is also a video here with the first three steps: 

https://github.com/flawiddsouza/Restfox/assets/41715438/66c93ac9-5f6a-411a-a7b9-fbcc7470a89f

> I don't think these two issues should have anything to do with the url and script content. If necessary, you can tell me and I will paste these contents.

**Comment by flawiddsouza** [comment]
Hi, I've published a new version: https://github.com/flawiddsouza/Restfox/releases/tag/v0.12.0. It should fix the above issues.
