### ISSUE TITLE
0.12.0 x64 for macOS

### ISSUE THREAD

**Issue by krehel** [flawiddsouza/Restfox#126]
Hi 👋  Homebrew maintainer here.

Previously we've made versions for Restfox available that were for x64.  The 0.12.0 release seems to be Apple Silicon only.  Are there plans to release an x64 build?

Thanks

**Comment by flawiddsouza** [comment]
Hi. Sorry about that. We haven't changed anything in the build pipeline. We're using macos-latest runner on github actions and it seems github has changed the macos-latest to be arm64 only. https://github.com/actions/runner-images/issues/9732#issuecomment-2080020545. Let me fix that, so both binaries will be available.

**Comment by flawiddsouza** [comment]
@krehel It's now added to https://github.com/flawiddsouza/Restfox/releases/tag/v0.12.0:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/f58839bc-dd2f-46db-b2c0-4c9b1ad789e1)

**Comment by krehel** [comment]
Awesome, thank you @flawiddsouza!
