### ISSUE TITLE
fetchSync certificate verification and script environment variable issues

### ISSUE THREAD

**Issue by mofazhe** [flawiddsouza/Restfox#127]
1. How to disable https certificate verification for fetchSync in a script.
![image](https://github.com/flawiddsouza/Restfox/assets/41715438/88df3b53-a577-416a-918e-7059a8a50bfe)
![image](https://github.com/flawiddsouza/Restfox/assets/41715438/f82b63e6-e256-4b10-af7f-4eda6edb4be8)
2. Can't use environment variables in script.
![image](https://github.com/flawiddsouza/Restfox/assets/41715438/c4ba411b-f94e-428a-8158-2c7171ae661c)

**Comment by flawiddsouza** [comment]
Hi, you can use this method to get an env var in a script:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/4f344999-c940-4cbd-96e3-087ec0098732)
Source: https://docs.restfox.dev/plugins/available-methods.html

It seems I haven't implemented the disable ssl flag for the http request that runs within a plugin. I'll fix that soon and let you know.

**Comment by flawiddsouza** [comment]
fetchSync now respects the disable ssl flag. It's available in the new version: https://github.com/flawiddsouza/Restfox/releases/tag/v0.13.0. Let me know if it works fine.
