### ISSUE TITLE
Invisible GraphQL body after v0.12.0 update

### ISSUE THREAD

**Issue by pims848** [flawiddsouza/Restfox#128]
Hi team,
Nice work you're doing.
Following v0.12.0 update I lost all my existing GraphQL queries in request bodies.
Looking closer the queries are still there but just not displayed: if I switch to JSON or plaintext I can see my queries unformatted.

Note: only the Query Variables are still displayed

Thanks for the fix.

**Comment by flawiddsouza** [comment]
Hi, sorry about that. Thanks for reporting the bug. This is now fixed and available in the new version: https://github.com/flawiddsouza/Restfox/releases/tag/v0.13.0.
