### ISSUE TITLE
Path variable not auto populating

### ISSUE THREAD

**Issue by yujinyuz** [flawiddsouza/Restfox#129]
Hi! I recently switched to this plugin after the Insomnia disaster that happened yesterday.

I'm still playing around with this and I think this would be a great alternative.

However, there is something that annoys me which is the path not being auto populated.

You can see a comparison with postman

https://github.com/flawiddsouza/Restfox/assets/10972027/3a205d41-7a25-4b96-85a2-773129e89aa8

**Comment by flawiddsouza** [comment]
This is definitely doable. Will implement this in a day or two.

**Comment by yujinyuz** [comment]
@flawiddsouza Thanks!

That was fast 💨
