### ISSUE TITLE
Support bulk-editing headers

### ISSUE THREAD

**Issue by infinitely0** [flawiddsouza/Restfox#13]
In Postman you can edit headers in bulk, which is very useful in cases where you want to paste the headers of a previous request and amend the body, for example. In Restfox you have to insert the headers one by one.

![image](https://user-images.githubusercontent.com/6633057/197803412-2f19091f-f61c-43cb-89b1-e2dd55b58b84.png)

I don't expect this would be too difficult to add. You'd just need to parse the line-separated headers in a textbox and update your list of headers.

**Comment by flawiddsouza** [comment]
Implemented in #101.
