### ISSUE TITLE
Add Javascript Console

### ISSUE THREAD

**Issue by eznix86** [flawiddsouza/Restfox#130]
Since we have scripts, and plugins, it would be interesting to have a console to preview everything being executed, because doing into Developer Mode is a bit of a hack.

At least we can have the result in a console within the context of the workspace. So it is easy to debug. What do you think?

**Comment by flawiddsouza** [comment]
Sounds like a good idea. I have thought of it before but making the ui for it would be quite a hassle. What kind of a ui do you envision for this? I'd love to hear some ideas.

**Comment by eznix86** [comment]
I do not think we shoukd have a log per request. Because some scripts and plugins mingle with each other with environment.

Logs with just log/print is not helpful. I believe a log with capability for showing line by line what has been executed and what are the errors.

The idea is not to dive into developer tool to see errors and see scripts running.

If we can see the whole execution history with errors that would be great, if it is per workspace it is better.

But i think if we have a console it should be used for debugging and follow-up purposes. Else better not do it.

**Comment by flawiddsouza** [comment]
Hey @eznix86

> I believe a log with capability for showing line by line what has been executed and what are the errors.

Can you expand on this line? Is there any software where you've seen something like this? So we have something for reference. I thought you were asking for simple print logging initially.

**Comment by eznix86** [comment]
@flawiddsouza 

@kobenguyent shared exactly what should show but on a workspace/global level.

Instead of json you should see logs with timestamp. Like what has been executed and its result and also see errors.

Basically the console works like a REPL.

https://nodejs.org/en/learn/command-line/how-to-use-the-nodejs-repl
