### ISSUE TITLE
Conflict when using path with ports

### ISSUE THREAD

**Issue by yujinyuz** [flawiddsouza/Restfox#131]
The port number is also being included in the path which isn't the desired behavior.

<img width="1030" alt="image" src="https://github.com/flawiddsouza/Restfox/assets/10972027/5d42bdda-bea8-40ad-b2ef-7c0bdec153d6">

I think it should just perform the match with the string

**Comment by flawiddsouza** [comment]
Just noticed this as well. I've pushed a fix. Releasing a hotfix version in a few minutes.

**Comment by flawiddsouza** [comment]
Released: https://github.com/flawiddsouza/Restfox/releases/tag/v0.14.1. Sorry about that. It's hard to foresee everything that can go wrong when implementing stuff like this.

**Comment by yujinyuz** [comment]
@flawiddsouza no worries! it wasn't a big deal.

Anyway, thanks for the fast update!
