### ISSUE TITLE
Mapping the status code with its status text

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#149]
Would be nice to map the status code with its status text.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses

![Screenshot 2024-05-14 at 11 19 11](https://github.com/flawiddsouza/Restfox/assets/7845001/4253c792-48e4-44d5-a2e3-f4c332a49a3b)

**Comment by flawiddsouza** [comment]
This should be doable. We need to maintain the constants for mapping and then display the mapped status text in Response Panel if the status text is response is empty.
