### ISSUE TITLE
Having `brew install restfox` would be nice

### ISSUE THREAD

**Issue by kolpav** [flawiddsouza/Restfox#15]
I think having single command installs would result in few benefits
- more users
- upgrades
- most of the users running the latest version
- - security patches
- - you could assume issues are about current version
- retention of users. I use [brewfile](https://thoughtbot.com/blog/brewfile-a-gemfile-but-for-homebrew) to keep track of things I want to keep between os reinstalls

From top of my head on mac there is `brew`/`nix-darwin`, win has `choco` maybe others and on linux all of the million package managers currently in use + snap.

**Comment by flawiddsouza** [comment]
My lack of a macOS system might be a blocker for this. I'll see what I can do. I'd be glad to accept some help on this.

**Comment by Tha14** [comment]
I'm working on it.

**Comment by Tha14** [comment]
@flawiddsouza You're going to have to sign Restfox.app
I've written a cask formula and it works so all that remains is for you to sign the app and we can make a pull request to add it to homebrew.

**Comment by flawiddsouza** [comment]
@Tha14 Thanks for the help. From what I just read online, for code signing, I'll need to get a apple developer account and have to pay 99$ per year for the fees. I don't know if it's worth it for a free open source application. Wish there was an alternative.

**Comment by Tha14** [comment]
> @Tha14 Thanks for the help. From what I just read online, for code signing, I'll need to get a apple developer account and have to pay 99$ per year for the fees. I don't know if it's worth it for a free open source application. Wish there was an alternative.

I'm fine with signing it for you, and I can maintaining the cask(that's super easy). Let me know if you feel like doing that.

**Comment by flawiddsouza** [comment]
If you're okay with maintaining it. Please go ahead. Let me know what you need.

**Comment by Tha14** [comment]
@flawiddsouza Sure, send me an email at github[at]plastiras.org and I'll let you know what needs to be done.

**Comment by Tha14** [comment]
I've created a pull request on the homebrew cask repo: https://github.com/Homebrew/homebrew-cask/pull/135504
Hopefully it goes smoothly.

**Comment by Tha14** [comment]
It's been merged :)
@kolpav You can now install it with homebrew.
