### ISSUE TITLE
trouble with url being mutated by restfox?

### ISSUE THREAD

**Issue by iceisfun** [flawiddsouza/Restfox#154]
When making requests to URLs that include colons in the path segment (e.g., MAC addresses), the path is incorrectly mutated. Specifically, when invoking a URL like https://testing-domain/backend/device/aa:bb:cc:dd:ee:ff/data, the expected path is altered to https://testing-domain/backend/device/aa/data

Testing with simple python3 http module and http://localhost:8000/device/aa:bb:cc:dd:ee:ff/data we get POST /device/aa/data HTTP/1.1

I found this while testing an existing api that implemented this in url parameter and assumed it was a bug on the backend service at first.

**Comment by flawiddsouza** [comment]
Thanks for reporting this. Let me look into this.
