### ISSUE TITLE
Trouble with request parameters containing "=" char

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#156]
I use a rest service (not from me ;-)) that unfortunately has a parameter which contains key value pairs:

```
https://my.com/endpoint?param=filter1=a,filter2=b
```
The parameter "param" has a string value "filter1=a,filter2=b".

Enter this URL in the request tab, switch to another tab and back again. The URL changes to

```
https://my.com/endpoint?param=filter1&param=filter1=a,filter2=b
```

I tried to work around it by masking the second "=" sign:

```
https://my.com/endpoint?param=filter1%3Da,filter2=b
```

But this does not work either, and the sent request now is completely weird:

```
https://my.com/endpoint?param=filter1%3Da%2Cfilter2%3Db&param=filter1&param=filter1%253Da%2Cfilter2%253Db
```

Is there a workaround for handling this? I hope that this is something that Restfox can fix, but I could not define a rule for URL parameter parsing ;-).

**Comment by flawiddsouza** [comment]
Thanks for reporting the bug. Let me look into this.

**Comment by WolfgangHG** [comment]
Whow, this was fast - the fix probably took less time than writing the issue ;-)!

**Comment by flawiddsouza** [comment]
Fix has been released: https://github.com/flawiddsouza/Restfox/releases/tag/v0.16.0. Please check and let me know if it's working correctly now.

**Comment by WolfgangHG** [comment]
Works perfectly, thanks!
