### ISSUE TITLE
Insomnium in import list

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#158]
https://github.com/ArchGPT/insomnium?tab=readme-ov-file#current-status

Due to another related project, this repo is no longer being actively maintained. Shall we consider removing it from the import list?

![Screenshot 2024-05-17 at 13 09 43](https://github.com/flawiddsouza/Restfox/assets/7845001/4caf8cca-aff3-460e-a822-4c348f257a5b)

**Comment by flawiddsouza** [comment]
Very unexpected. I thought that project had good traction. I guess we can remove it then. But I wonder if we should just let it be for now for people who want to migrate from it to Restfox. We can remove it in a few months.
