### ISSUE TITLE
Environment Var dropdown introduces a 'space' between key and brace

### ISSUE THREAD

**Issue by ricktimmis-xia** [flawiddsouza/Restfox#168]
**Current Behaviour**
Automatic dropdown for Environment Variable selection, adds a space between the variable name and the }. This means these variables do not resolve to their value.

**Expected Behavior**
Selections from the dropdown should resolve to their reference correctly, and go green. See example screenshot below.

Shot 1 - Dropdown
![image](https://github.com/flawiddsouza/Restfox/assets/84178956/bd6e2920-2a5a-4450-ac30-fccf8a4ecfb9)

Shot 2 - Note {{OCAPI_USER_LOGIN }} has a trailing space.
![image](https://github.com/flawiddsouza/Restfox/assets/84178956/d9ff8a90-c27e-4fa8-bead-722693446c6c)

Shot 3 - Removal of space and variable correctly resolves
![image](https://github.com/flawiddsouza/Restfox/assets/84178956/b23d1336-83ec-4a53-9c9a-533f5e7b6f00)

**Steps to reproduce**

1. Add one or more variables into an Environment
2. Goto 'Auth Basic' tab
3. Begin typing at Env Var value
4. Select choice from the Dropdown
5. Notice a space added before the closing bracket

_Also, as I typed up this ticket, I discovered that it you just begin typing the Env Var name without double opening brace '{{' when you select from the dropdown the prefix braces are omitted, but the suffix braces are applied but with a space_

**System and Version**

Kubuntu 24.04 LTS

Restfox installed via snap package:

`name:      restfox
summary:   Lightweight REST / HTTP Client
publisher: Artelin (flawid)
store-url: https://snapcraft.io/restfox
license:   unset
description: |
  A lightweight REST / HTTP Client based on Insomnia and Postman.
  
  Features:
  - Workspaces
  - Tabs
  - Nested Folders
  - Lots of context menus
  - Response history
  - Plugins
  - GraphQL support
  - Import collections exported from Postman and Insomnia
  - Simple user friendly interface
commands:
  - restfox
snap-id:      5F3RdI1tJO2Fj4oHj05gtSmT7osdZmDm
tracking:     latest/stable
refresh-date: yesterday at 15:59 BST
channels:
  latest/stable:    0.18.0 2024-06-25 (39) 92MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      ↑                           
installed:          0.18.0            (39) 92MB -
`

**Comment by flawiddsouza** [comment]
Some users like writing env vars without spaces, so when they type and accept the auto complete:
This:
```
{{M
```
becomes:
```
{{MyAutoCompletedVar }}
```

Valid:
`{{ MyAutoCompletedVar }}` one space at the beginning and one at the end
`{{MyAutoCompletedVar}}` no space at the beginning and end

Invalid:
`{{MyAutoCompletedVar }}` no space at the beginning but one space at the end
`{{ MyAutoCompletedVar}}` one space at the beginning but no space at the end

So we need to do 3 things.

1) If user starts typing `{{M` and accepts auto complete, it should become `{{MyAutoCompletedVar}}`
2) If user starts typing `{{ M` and accepts auto complete, it should become `{{ MyAutoCompletedVar }}`
3) If user starts typing `M` without `{{` or `{{ ` at the beginning, it should become `{{MyAutoCompletedVar}}`

All the logic required most likely should be doable inside this:

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/155d791e-bbee-437e-8635-aecd38ad289b)
It might be a bit complex as there's a bit of backtracking involved. To check for the `{{` and `{{ `

@kobenguyent Do you want to pick this up?

**Comment by flawiddsouza** [comment]
@kobenguyent This is good but I want users to have the choice of using the software how they want, rather than how we want them to use it. People have different behaviors and it's always nice to account for them.

Also, with this change, if a user starts typing `{{ u` and accepts auto complete, it will be come `{{ {{ user }}`

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/084df9e9-43ba-4b2f-a1ed-246b4a70b717)

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/d135e7e6-515b-4eaf-9f20-ff4443306ffe)

They'll have to delete the first few characters, which can be quite annoying if happens again and again.
