### ISSUE TITLE
How would one run this sa it is on https://restfox.dev/

### ISSUE THREAD

**Issue by Leopere** [flawiddsouza/Restfox#18]
I really would prefer to have this behind a reverse proxy on my dev cluster.  Can there be instructions on how to build this without electron so I can run whats at https://restfox.dev/ within my private walled garden.

**Comment by flawiddsouza** [comment]
Hi, as there's no backend behind the application, there are only static files that you need to host.

Follow these steps to generate the static files:
```
git clone https://github.com/flawiddsouza/Restfox
cd packages/ui
npm i
npm run build
```
Then copy everything in `packages/ui/dist` into a publicly served folder on your dev cluster and expose it through a https endpoint. These generated files are exactly what's served at [restfox.dev](https://restfox.dev) without any modifications.

This will still sadly not give you the power to send non CORS and non https requests. For [restfox.dev](https://restfox.dev), that power is granted by the [chrome](https://chrome.google.com/webstore/detail/restfox-cors-helper/pgoncladmcclnmilkbnmmbldcihdgfnf) / [firefox](https://addons.mozilla.org/en-US/firefox/addon/restfox-cors-helper/) extensions on the browser (which are currently only whitelisted for [restfox.dev](https://restfox.dev)). These need to be separately installed by the user.

On Electron, non cors and http requests just go through without any bypass required.

[restfox.dev](https://restfox.dev) does not send your requests to a backend server and all requests are processed in the browser itself.

Maybe we can have a backend server that one can host to proxy all requests made from the app. This does not exist yet but would allow you to use restfox without electron or the chrome extensions.

**Comment by flawiddsouza** [comment]
@Leopere I went ahead and implemented a separate package for running Restfox standalone without needing electron or the browser extensions.

The instructions for running this version can be found at: [README.md#using-web-standalone](https://github.com/flawiddsouza/Restfox#using-web-standalone). I'm also putting them here:
```
git clone https://github.com/flawiddsouza/Restfox
cd packages/ui
npm i
npm run build-web-standalone
cd ../web-standalone
npm i
npm start
```
By default npm start will run Restfox at port 4004. You can override the port by passing port like so `PORT=5040` npm start.

Hope you find this useful.

**Comment by flawiddsouza** [comment]
@Leopere I went ahead and implemented a separate package for running Restfox standalone without needing electron or the browser extensions.

The instructions for running this version can be found at: [README.md#using-web-standalone](https://github.com/flawiddsouza/Restfox#using-web-standalone). I'm also putting them here:
```
git clone https://github.com/flawiddsouza/Restfox
cd packages/ui
npm i
npm run build-web-standalone
cd ../web-standalone
npm i
npm start
```
By default npm start will run Restfox at port 4004. You can override the port by passing port like so `PORT=5040 npm start`.

Hope you find this useful.

**Comment by iuv** [comment]
@flawiddsouza  Hi~ I refer to this and visit localhost:4004 after startup, it prompts me 404, where is there a problem with the operation?

**Comment by flawiddsouza** [comment]
Hi @iuv, that would happen if the ui wasn't built. I just went through the same flow and  I was also able to get the 404 error. To fix, run:
```
cd packages/ui
npm run build
cd ../web-standalone
npm start
```
We're basically just rebuilding the ui. There's definitely an issue with the build but I'm not able to figure it out for now. It seems to disappear as soon as we run `npm run build` twice.

**Comment by iuv** [comment]
@flawiddsouza  Uh...I tried it. The problem still exists here. Is it a nodejs version problem? I use the latest version

**Comment by iuv** [comment]
Uh... I looked and I'm using nodejs16
Didn't output any error logs, I ran it on this website: https://labs.play-with-docker.com/
You can try it, the command I executed is as follows:
```sh
apk update
apk add nodejs
apk add npm
git clone https://github.com/flawiddsouza/Restfox
cd Restfox/packages/ui
npm i
npm run build-web-standalone
cd ../web-standalone
npm i
npm start
```
Then access the 4004 port through the top `OPEN PORT`, it will return 404, and execute it again according to your method:
```sh
cd ../ui
npm run build
cd ../web-standalone
npm start
```
Visited again, the problem still exists

**Comment by flawiddsouza** [comment]
@iuv The issue is pretty clear now that I ran the commands in the https://labs.play-with-docker.com environment. `npm run build-web-standalone` is unable to create the required `public` folder in the `packages/web-standalone` folder with the built ui files. So we have to do the copy of the built files manually. Seems like this is an issue with the copying of files. Here are the updated steps for your environment:

```
apk update
apk add nodejs
apk add npm
git clone https://github.com/flawiddsouza/Restfox
cd Restfox/packages/ui
npm i
npm run build-web-standalone
cp dist/* ../web-standalone/public -r # this is the fix
cd ../web-standalone
npm i
npm start
```

**Comment by iuv** [comment]
This ok, I built a mirror `docker pull kiis/restfox:0.0.7`  
I submitted a PR for the relevant code, you can see if it can be merged into it.

**Comment by Leopere** [comment]
I ended up suffering a brainstem injury in february but now I'm recovering I'm glad to see movement on this it seems it would be a pretty slick tool to self host for my team.
