### ISSUE TITLE
Repeated application/x-www-form-urlencoded fields only send final field

### ISSUE THREAD

**Issue by nikclayton** [flawiddsouza/Restfox#180]
It's possible to have an `application/x-www-form-urlencoded` `POST` request that has multiple fields with the same name.

For example, https://docs.joinmastodon.org/methods/filters/#create.

If you try and do this in Restfox only the last field value is sent.

To reproduce:

1. Create a new request
2. Set the method to `POST`, the url to `https://mastodon.social/api/v2/filters`
3. Set the body to "Form URL Encoded"
4. Add two items, both with name `data[]`, set the value of the first to `one`, the second to `two`.
5. Send the request
6. The request will fail because you're not authorised. 
7. Open the "Request" tab in the Restfox UI

You'll see the request was `data%5B%5D=two`.

It should be `data%5B%5D=one&data%5B%5D=two`.

If you have the network inspector open when you send the request at step 5 you'll confirm the wrong form data was sent.

**Comment by flawiddsouza** [comment]
That makes sense. Let me look into fixing that.

**Comment by flawiddsouza** [comment]
Issue is fixed now.

Before:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/48cc1fef-4508-4cb0-88d9-04246880d9eb)

After:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/c37e02c2-7cd3-4387-a547-70e8ab15e188)

Already deployed to https://restfox.dev. For the desktop release, it might take a few days.

**Comment by nikclayton** [comment]
Great, thanks.
