### ISSUE TITLE
Deformed UI after snapping to side on windows

### ISSUE THREAD

**Issue by alinz76** [flawiddsouza/Restfox#190]
Hey Dude!
Thanks for such a great app😊

On Windows after snapping app to a side, the UI shapes like attached photo.
but on Fullscreen mode there is no such issue

![Screenshot 2024-07-21 022116](https://github.com/user-attachments/assets/a7858562-0ab4-4f31-9d7e-c048167d9af6)

**Comment by flawiddsouza** [comment]
I'm glad you like the app. I've fixed this issue and it should be available in the next release. Next release would be happening in the next 2 or 3 weeks.
