### ISSUE TITLE
[FR] - Auth, Headers, Env, Docs at Collection or Folder level 

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#199]
Just noticed  Auth, Headers, Env, Docs at Collection or Folder level would bring also more benefits for example when setting the Auth at collection or folder level all children requests would inherit them on the fly.

![Screenshot 2024-07-26 at 07 51 16](https://github.com/user-attachments/assets/04bb5f06-5e60-47dc-8b36-83136e0b6325)

**Comment by flawiddsouza** [comment]
Auth, headers and env are already present on the folder level:
![image](https://github.com/user-attachments/assets/a06b5025-9658-4a98-a27f-15b299737092)
![image](https://github.com/user-attachments/assets/af991fab-77c9-4264-a1d0-588cd177e486)

Currently auth and headers are inherited by default. There's no way to disable it on the request level. Only on the folder level.

No docs option is present on the folder level.

I don't want folders to show a view like this on click:
![image](https://github.com/user-attachments/assets/8ebd3bc7-2439-481d-9fc3-4be34c088b71)
As I want folders to collapse and expand on click.
I'm not against giving a view like this by it should be through some other way than click of the item in the sidebar.
