### ISSUE TITLE
Please support authorization when fetching schema documentation GraphQL

### ISSUE THREAD

**Issue by rahmatalhakam** [flawiddsouza/Restfox#203]
Error:
1. I got Error fetching schema: URL constructor: {{url_dev}} is not a valid URL. This error happened because i use the env for url
![image](https://github.com/user-attachments/assets/79e7916d-a295-427b-b243-65a03af16d77)
2. When i try to change the url, i got error 401. Please add the authorizarion in header when fetching graphql documentation.
![image](https://github.com/user-attachments/assets/194a715c-78f5-4f46-97f4-716e1a4bd1d2)

Feature request
1. My schema is quite big (5.2 MB). Can you add a setting to not always fetching schema again after I SEND the graphql query/mutation? It was frustrating to wait documentation until finish, especially when the connection is not good.
![image](https://github.com/user-attachments/assets/b0ab8e15-67c5-476f-9a5e-80e98f5802b1)

**Comment by flawiddsouza** [comment]
> Can you add a setting to not always fetching schema again after I SEND the graphql query/mutation
As far as I know, the schema is fetched when you click Show Documentation button. Maybe we can cache that after the first time we fetch it. From your last screenshot, it looks like you're fetching the schema as a request. Was that just for demo purposes to show the size of the schema and time taken?

**Comment by flawiddsouza** [comment]
> Can you add a setting to not always fetching schema again after I SEND the graphql query/mutation

As far as I know, the schema is fetched when you click Show Documentation button. Maybe we can cache that after the first time we fetch it. From your last screenshot, it looks like you're fetching the schema as a request. Was that just for demo purposes to show the size of the schema and time taken?

**Comment by rahmatalhakam** [comment]
> > Can you add a setting to not always fetching schema again after I SEND the graphql query/mutation
> 
> As far as I know, the schema is fetched when you click Show Documentation button. Maybe we can cache that after the first time we fetch it. From your last screenshot, it looks like you're fetching the schema as a request. Was that just for demo purposes to show the size of the schema and time taken?

Hmm when I try to Show Documentation button, no request was recorded in Network. But as far as I know, the schema is fetched when I try to type on url (video attached). I don't know it is the expected behavior or not.


https://github.com/user-attachments/assets/d90ef6c7-6383-4ce2-8051-fb1fee279e6d



Oh okay, if the schema is not always fetched after I click Send button, so it was not a problem. Maybe I confuse between the Restfox and the Insomnia (in this case, Insomnia always fetches schema after click send button). Hahaha. I will inform you after 2 bugs above fixed.

**Comment by flawiddsouza** [comment]
Hey @kobenguyent Can we avoid fetching the schema every time the user changes the url? Instead let's fetch the schema when user clicks show documentation once and then offer a refresh button in show documentations drawer or a refresh documentation button beside the show documentations button. This is not as fast to update but it's much better than fetching 10 MB of schema on every key press.
