### ISSUE TITLE
"Ctrl+End" in result view window

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#208]
Just noticed this small issue: I am use to go to the end of a textbox by pressing "Ctrl+End".
This does not work in the result view - in my sample it display lines 30 to 49 (which is not even the next scroll page):
![preview1](https://github.com/user-attachments/assets/73e282ed-cd49-4334-a97e-5578c8240b0e)

The reverse ("Ctrl+Pos1") works as expected.

**Comment by flawiddsouza** [comment]
You're right. Ctrl + End seems to act like page down. If you keep pressing it, it keeps scrolling down. Ctrl + Home (or Pos1 for you) seems to work fine and take me to the beginning like you said. Let me look into this. No code related to this has changed. I think this behavior is seen when your response is really long. Else it works as expected.

**Comment by WolfgangHG** [comment]
Yeah, it works! Thanks!
