### ISSUE TITLE
[FR] - Fast access and switch to any Workspace

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#210]
That'll be nice to have an option to switch to another workplace on the fly
![Screenshot 2024-08-09 at 11 52 27](https://github.com/user-attachments/assets/3e413020-67d9-4a24-b652-addff6f2f023)

**Comment by flawiddsouza** [comment]
Seems like a good feature.

**Comment by flawiddsouza** [comment]
Hi @kobenguyent, are you working on this? I'm asking because I wanted to pick this up and I don't want to work on it if you're already working on it.
