### ISSUE TITLE
Support highlighting of hyphenated environment variables

### ISSUE THREAD

**Issue by salittle0** [flawiddsouza/Restfox#211]
Environment variables with a hyphenated name are injected into requests correctly, but they aren't highlighted/resolved on-hover in the UI. I assume this is a bug because of the mismatch in injection/highlighting behaviour, but it could be a feature request.

As an example, if you have the environment file
```json
{
    "my_key": "underscore",
    "my-key": "hyphen"
}
```
Then a request using both environment variables correctly highlights the one with the underscore only.
![restfox-2](https://github.com/user-attachments/assets/b748be01-9eba-42b6-bb6c-c4432010b925)

I'm not very familiar with this code/what it's built with, but it might be enough to update the regex in `codemirror-extensions.ts` to include a hyphen
```javascript
// current
export const variableMatchingRegex = /{{ ([.|\w]*?) }}|{{([.|\w]*?)}}/g

// new
export const variableMatchingRegex = /{{ ([-.|\w]*?) }}|{{([-.|\w]*?)}}/g
```

Side note: the current regex specifically includes the vertical bar (|), so an environment variable such as `my|key` would inject/highlight correctly.

**Comment by flawiddsouza** [comment]
Hi, this looks like a bug since the substitution behavior doesn't match the highlighting. Will fix this soon.
