### ISSUE TITLE
RestFox delete all of my Desktop folders!!!

### ISSUE THREAD

**Issue by Jacksonant** [flawiddsouza/Restfox#215]
I created a collection whichi point to my Desktop (root path). 
After I clicked to delete the coolection, it removed all of my Desktop folders!!!
Any way to restore all of my deleted folders in Desktop??!!
There is no  backup for thise folders

![image](https://github.com/user-attachments/assets/7182f8ee-704e-4901-b16b-2af2ea68f87b)

**Comment by flawiddsouza** [comment]
Hi, I'm really sorry about this. A Restfox collection should not be pointed to a root path like this. Restfox will try to delete all folders found inside its collection when deleting a collection. I'll be changing this behavior to protect against accidental deletion like this.

For recovering the deleted folders, you can try using a free recovery software like Recuva (https://www.ccleaner.com/recuva/download/standard) if you're on Windows. If you're on another OS, googling should lead you to one of the popular free software for file recovery. They can usually recover the deleted files if nothing has overwritten them.
