### ISSUE TITLE
The version from https://restfox.dev/ is not the latest version

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#216]
I'm not sure if that's intended or a bug as the version is not the latest one. Let's say one commit behind.
![Screenshot 2024-08-14 at 09 16 59](https://github.com/user-attachments/assets/ea06b09f-3cdb-4454-812c-040ab6102c7a)
![Screenshot 2024-08-14 at 09 17 09](https://github.com/user-attachments/assets/932290da-c790-4a47-9a3c-beb2e500ddf3)

**Comment by flawiddsouza** [comment]
Hi, Restfox deployment to https://restfox.dev is currently a manual process. That's the reason it's behind one commit. Functionally it's the same features as the last version, minus the version bump.
