### ISSUE TITLE
Pre-script / Post script is not imported

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#217]
well, just noticed one thing, when importing the postman collections, Pre-script / Post script is not imported. I'd think, it'll be nice to import them into restfox, then user could somehow adjust them later on to make it work with restfox.

Comparing to Insomnia however, importing them.
![Screenshot 2024-08-14 at 13 36 27](https://github.com/user-attachments/assets/a2578f4a-2dd5-4bfd-a7f1-238c7549c9f7)

**Comment by flawiddsouza** [comment]
Scripts were introduced pretty recently. In April: https://github.com/flawiddsouza/Restfox/releases/tag/v0.9.0. Sounds like a good idea to import them. Concern is that requests will error out after they import for the first time. As there's no one-to-one conversion.

Is Insomnia importing the scripts as is, without any conversion?
