### ISSUE TITLE
Add Path Parameters

### ISSUE THREAD

**Issue by sboulema** [flawiddsouza/Restfox#22]
Great work on Restfox! Love it.

Feature request:
Ability to easily add path parameters instead of query parameters. 

In Postman you can add a path parameter by using ":" instead of "{{}}" for environment variables.

![image](https://user-images.githubusercontent.com/1820661/201939827-57670eda-2118-4d62-ae60-9a73ded572ec.png)

**Comment by flawiddsouza** [comment]
@sboulema This is now availabe here:
![image](https://user-images.githubusercontent.com/10164500/202109751-e9302497-607d-4f4a-9efe-7825403975ee.png)
