### ISSUE TITLE
Sidebar > Sidebar item > Active item indicator

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#225]
what do you think if we just show like this for active item?
![Screenshot 2024-08-16 at 15 49 26](https://github.com/user-attachments/assets/8348140b-8e6b-4c4e-8c77-c32eb8f91bd6)

It is used like this in Teams
![Screenshot 2024-08-16 at 15 51 48](https://github.com/user-attachments/assets/9e780126-15c0-499b-af0e-15a38b738db1)

Insomnia
![Screenshot 2024-08-16 at 15 52 38](https://github.com/user-attachments/assets/ca8a2aee-52b6-4512-811c-ec228a15708a)

**Comment by flawiddsouza** [comment]
I'd like to keep the active border and background as they are. Even though this works for the above apps. It actually makes the existing usability worse. I'm not a fan of that design. If you notice, they also fill the icon + change the icon color to make it more observable. Issues which don't need to be addressed, when you have the whole item being highlighted all around.

**Comment by flawiddsouza** [comment]
The more I think about it. I feel like we should have some kind of a custom theming system, so people can make their own designs and the customize the ui to their liking.
