### ISSUE TITLE
The snap version cannot enter Chinese characters

### ISSUE THREAD

**Issue by liaohongxing** [flawiddsouza/Restfox#229]
The snap version cannot type Chinese characters, but snap's Firefox can type Chinese characters, which seems to be related to the snap framework

ibus:
```
sudo apt install ibus-libpinyin
```

restfox snap version: 
```
0.23.0
```

**Comment by flawiddsouza** [comment]
Hi, I'll need a bit of help with this. I installed `ibus-libpinyin`. What's the next step to follow to open the input? I'm on Ubuntu. I'm not familiar with pinyin input, so if there's a guide somewhere I can follow, that would be help me check this.

**Comment by liaohongxing** [comment]
ubuntu gnome desktop

step1: 
```
open setting => keyboard => input sources =>  add input sources => click ... =>  other =>  choose  chinese( intelligent pinyin)  => click Add
```

step2:
```
press   super (win) + space  key  switch chinese input 
```

**Comment by flawiddsouza** [comment]
Hi @liaohongxing Was the issue resolved?

**Comment by liaohongxing** [comment]
@flawiddsouza 
The problem is not solved. I have given up the snap version and switched to deb installation.

**Comment by flawiddsouza** [comment]
Looks like this is a known issue with snap: https://forum.snapcraft.io/t/cant-use-input-method-in-snap-apps/4712. Sadly not something that can be fixed until the snap team fixes it. Using deb is the right call.
