### ISSUE TITLE
Restfox env exported data

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#231]
![Screenshot 2024-09-02 at 09 45 28](https://github.com/user-attachments/assets/d917258c-f10b-4988-bd7f-069df9e5f2af)
out of curiosity, I see headers in env data, not sure if that's intended like that.

**Comment by flawiddsouza** [comment]
Just exported two different workspaces of mine and did not get this. I think you might've pasted your headers into environment maybe? Can you check?
