### ISSUE TITLE
Folder properties as view instead of a popup when clicking on the Folder

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#235]
![Screenshot 2024-09-06 at 10 34 06](https://github.com/user-attachments/assets/9e063b44-53ba-44fa-8e15-74cc2048ed2c)

What do you think if we show folder properties as a view, I find it's quite a convenient way to have an overview of folder properties.

**Comment by flawiddsouza** [comment]
Do you mean as a tab? Sounds like a good idea.
