### ISSUE TITLE
Bulk Editing Headers from Folder Properties Closes Modal Instead of Bulk Editing

### ISSUE THREAD

**Issue by pckilgore** [flawiddsouza/Restfox#243]
<img width="609" alt="image" src="https://github.com/user-attachments/assets/18fbc65a-96eb-4d92-bb5d-b43582a6c63e">

**Comment by pckilgore** [comment]
The only reasonable OSS alternative is: https://github.com/EsperoTech/yaade

But I liked this one more.

**Comment by flawiddsouza** [comment]
Thanks for reporting this.
