### ISSUE TITLE
No active tab throws error when trying to read the url 

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#252]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'url') error when trying to read the url 

![Screenshot 2024-09-25 at 07 56 43](https://github.com/user-attachments/assets/ddd28a2b-cab3-4120-9007-60f770547329)

**Comment by flawiddsouza** [comment]
Heyo, can you list the reproduction steps?

**Comment by flawiddsouza** [comment]
Thanks. That helps. Looks like I can recreate the error if I just open a workspace without any tabs open.
