### ISSUE TITLE
No token is obtained when trying to request the oauth2 token

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#254]
https://github.com/user-attachments/assets/49f52c65-d0b3-46f2-a385-07bf1fbb2867

Steps:
- import a postman collection with oauth2 token at folder level
- now open folder properties
- click get token
- notice that toast says oauth2 token is obtained successfully
- now open folder properties again
- token field is still n/a

**Comment by flawiddsouza** [comment]
@kobenguyent I've pushed a fix https://github.com/flawiddsouza/Restfox/commit/ddb1b8dede8422924c492a8e0ac2f244743a3e0d and deployed to https://restfox.dev. I think earlier the modal was closing before the data got persisted. Can you check now?

**Comment by flawiddsouza** [comment]
Hey @kobenguyent, test-api-oauth2 now supports refresh token for grant type password. You can test at https://restfox.dev. It should be proper now.
