### ISSUE TITLE
oauth2.0 token at folder level isn't applied to all requests of its subfolders

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#255]
1. Get oauth2.0 at folder level
2. try to make a request at a subfolder
3. **No oauth2.0 token is applied**.

**Comment by flawiddsouza** [comment]
![image](https://github.com/user-attachments/assets/f0e2cf97-c21a-4b99-8125-78e4898a3740)
Looks like there's no logic to handle oauth2.

It's not just at the folder level, on the request level also, the auth type oauth2 is not working then.
