### ISSUE TITLE
[Hacktoberfest] To attract more contributors

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#270]
https://hacktoberfest.com/participation/#pr-mr-details

[participating] Your PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label.

**Comment by flawiddsouza** [comment]
Topic added
![image](https://github.com/user-attachments/assets/95ac8693-8277-4c81-b47b-3dd26d244c36)
