### ISSUE TITLE
Making a request now triggers plugin/post-scripts of all requests

### ISSUE THREAD

**Issue by kobenguyent** [flawiddsouza/Restfox#278]
I imported a postman collection, some requests have post scripts, some don't. However when I call a request without postscript, looking into console logs, all post scripts are now triggered.

for instance this request has only one test, but it calls 100+ tests from other requests.

![Screenshot 2024-10-11 at 09 51 13](https://github.com/user-attachments/assets/69e19754-28e6-4d58-9900-84f9fa5ef677)

![Screenshot 2024-10-11 at 09 47 50](https://github.com/user-attachments/assets/a699e72c-7011-48a6-b0c5-298772dd2e77)

**Comment by flawiddsouza** [comment]
I have been suspecting that there might be a bug in the import code. Related to postman.

Check your plugins in the navbar just in case. I have seen some stray global plugins appear.

Also, this seems like there are multiple scripts attached to the same collection id. Can you send your postman collection here (removing all sensitive data) so I can debug and fix this?

**Comment by flawiddsouza** [comment]
Thanks that really helped. Issue is that imported scripts have workspaceId filled for plugins data:
![image](https://github.com/user-attachments/assets/1ed652b1-13d8-44f2-818a-254b6644df7c)

This shouldn't happen as anything with workspaceId is considered a workspace level plugin. I've pushed a fix.

**Comment by flawiddsouza** [comment]
> not sure if that's related but when I have script on top folder, importing into restfox, shall we convert it as plugins? ![Screenshot 2024-10-11 at 11 16 49](https://private-user-images.githubusercontent.com/7845001/375700029-5c7b8846-28f6-45d9-9e3a-46287ca77616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTcwNDIsIm5iZiI6MTcyODY1Njc0MiwicGF0aCI6Ii83ODQ1MDAxLzM3NTcwMDAyOS01YzdiODg0Ni0yOGY2LTQ1ZDktOWUzYS00NjI4N2NhNzc2MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTQyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA0MDI0M2U2NTRlOGNkYTY3YTU2NmYyOTQzNDdhZmI0YjAzZDYxOGEzZmQxZDc1YjgxZjQ5ZmI3ZWRjNjliMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ihDdHwvY66d74O4-tGMRbl5tsf1fcdueB3z9J-BLH2A)
> 
> Attached collection: [Debug.postman_collection.json](https://github.com/user-attachments/files/17340540/Debug.postman_collection.json)

Yes that should be good.

**Comment by flawiddsouza** [comment]
By the way, I'm really glad you caught this bug. I've noticed the random empty plugins once in a while in the workspace plugins list and it had been bothering me. Didn't know what was causing it. Had it in my todo list to check it out.

**Comment by flawiddsouza** [comment]
Send your PR. I'll look into it.
