### ISSUE TITLE
OAuth2: certificate validation error on localhost

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#283]
Just gave the OAuth2 flow from #247 a try (hopefully a great feature).

But it fails when accessing a localhost url with a self signed certificate.

First of all: when the error happens, there is only a popup "Error fetching OAuth token. Please check the console for more details". When hovering over this red error message, the cursor changes to something that seems to be clickable. But nothing happens on click. Is this intended?
![oauth2](https://github.com/user-attachments/assets/093ba0ae-e5e3-4c9d-8025-b89d7d159b69)

I think the message points me to the "Logs" button in top right?
Here I found this error:

```
08:29:06:296 - [ERROR] - Error fetching OAuth token: TypeError: fetch failed 
  at fetch (C:\Users\USERNAME\AppData\Local\Restfox\app-0.27.0\resources\app\node_modules\undici\index.js:112:13) 
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
  at async Object.handleSendRequest (C:\Users\USERNAME\AppData\Local\Restfox\app-0.27.0\resources\app\src\request.js:117:26) 
  at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:78381) 
Error: unable to verify the first certificate at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34) 
  at TLSSocket.emit (node:events:514:28) at TLSSocket._finishInit (node:_tls_wrap:1070:8) 
  at ssl.onhandshakedone (node:_tls_wrap:856:1
```

I disabled SSL verification in the settings:
![settings](https://github.com/user-attachments/assets/7f3ddd57-9d76-4c80-a2b5-3d1777a19f14)

Does the OAuth2 flow ignore this setting?

**Comment by flawiddsouza** [comment]
I think we missed respecting the disable ssl flag when making an oauth request. This is definitely a bug and will be fixed soon.

**Comment by flawiddsouza** [comment]
> When hovering over this red error message, the cursor changes to something that seems to be clickable. But nothing happens on click. Is this intended?

This is because the toast can be clicked on to dismiss it. It doesn't lead anywhere.

The error definitely needs to improve.

The issue has been fixed and there will be a new release in a few days.

**Comment by WolfgangHG** [comment]
I can confirm that it works. Many  thanks!
