### ISSUE TITLE
Support for total response time

### ISSUE THREAD

**Issue by kuche1991** [flawiddsouza/Restfox#285]
Hi,

at first: thx for the nice tool and the invest of time on your side.
I'm currently doing some testing on a streaming API and did notice, that the response time actually shows the time the response header took to transfer. It would be nice for a streaming request, to also show the total response time for the request (header + body). 

Kind regards,
kuche

**Comment by flawiddsouza** [comment]
Hi @kuche1991, can you let me know which OS you're using and how you installed the application?

The response time actually includes the time to fetch headers + body. Maybe streaming response bodies need a different mechanism for tracking time.

**Comment by kuche1991** [comment]
Thanks for the quick reply.

I am on Ubuntu 24.04.1 LTS and I installed it via snap, current version 0.28.0.
Attached I have a screen-video in which I query one of our APIs which streams a CSV.
It would be nice, if could see both response times (header complete and body complete).

[screen.webm](https://github.com/user-attachments/assets/719abbd8-1072-49a6-a84a-6d9436757018)

**Comment by flawiddsouza** [comment]
The seems very incorrect. Seems like a bug. Header complete + body complete isn't tracked separately for now. Will make a note to see if we can implement it.

**Comment by flawiddsouza** [comment]
This is now fixed in https://github.com/flawiddsouza/Restfox/commit/2ef4a7d4aee84e2dbc90a650bf940b450cbbbd92.

Also you will now be able to see head complete + body complete when hovering over time taken:
![image](https://github.com/user-attachments/assets/84cbe011-d5fa-4aa2-a402-def472d5f334)

**Comment by kuche1991** [comment]
Nice!
Thanks a lot for your work.
