### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [flawiddsouza/Restfox#288]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

Would be great (and convenient) to be able to install `Restfox` from `Flathub`. It would also acquire _visibility_ in the app stores automatically.

**Comment by flawiddsouza** [comment]
This has been requested here: https://github.com/flawiddsouza/Restfox/issues/71. The flow to get the app on flathub seems to be much more complex than other stores, so I've been having trouble making the time to get everything right. Electron packages for flathub also seem to be outdated. I'd happy to get a PR for this.
