### ISSUE TITLE
Path params missing when importing from postman collection

### ISSUE THREAD

**Issue by Dokkaltek** [flawiddsouza/Restfox#293]
First of all, thanks for creating such a wonderful application, it's fast and private and seems to be the only one that I have tried that fits all the use cases that I had on postman!

With that said, I found an issue while importing postman collections, where it won't import the path variables (The path variable is still shown on the uri).

![image](https://github.com/user-attachments/assets/651b593c-120e-4912-869a-2819cde7357b)

If I add the path variable manually or attempt to edit the url the path parameters will appear (although they appear with an empty value, even if we had any on postman).

[Path param.postman_collection.json](https://github.com/user-attachments/files/18231036/Path.param.postman_collection.json)

**Comment by flawiddsouza** [comment]
Thanks for including an export. I'll look into this.

**Comment by flawiddsouza** [comment]
Hi there's no path param is your given export:

![image](https://github.com/user-attachments/assets/439b83d8-8e3b-4972-bfd2-023a5aa7be6e)

Can you help me with the correct example export for the above bug?

**Comment by Dokkaltek** [comment]
Sorry, must have forgotten to add the actual path variable. I editted the original comment with the updated export having a path variable.

![image](https://github.com/user-attachments/assets/04e4e527-f3dc-4628-9c7a-a831b7d43841)
