### ISSUE TITLE
Save issues with filesystem workspace

### ISSUE THREAD

**Issue by Dokkaltek** [flawiddsouza/Restfox#295]
I found some issues when working on a workspace that was saved in filesystem instead of in application:

- When you import a collection from postman to restfox it won't let you rename the folder, and if you change the text with the properties popup open, it won't let you close it until you leave the name back to the original name it had.
- If you have any script on the scripts panel of a request, the next time you close and open restfox, those scripts will be gone, no matter if you created the request from restfox, or imported it from postman. The same will happen to any plugins you had on the collection.
- If you export a collection from restfox in filesystem mode, when you try to re-import it on another workspace it will have deleted the plugins and the scripts.

**Comment by Dokkaltek** [comment]
Sample restfox collections. Both were exported with a sample folder with a sample plugin and a sample request with a sample pre and post script.
[test-export-in-app.json](https://github.com/user-attachments/files/18111203/test-export-in-app.json)
[test-export-in-filesystem.json](https://github.com/user-attachments/files/18111204/test-export-in-filesystem.json)

**Comment by flawiddsouza** [comment]
Regarding point 2 and point 3, can you try the latest version: https://github.com/flawiddsouza/Restfox/releases/tag/v0.32.0? I pushed some fixes. I seem to have broken the plugin retrieval code when I made some changes in the last update. Plus I found an issue in the workspace plugins code, so you should see your scripts and plugins correctly now.

> When you import a collection from postman to restfox it won't let you rename the folder, and if you change the text with the properties popup open, it won't let you close it until you leave the name back to the original name it had.

I'll look into this. Seems like a weird bug.

**Comment by Dokkaltek** [comment]
Thank you, it seems like the scripts are being imported correctly now.

As for point 1, it seems like it won't happen with small collections which don't have embedded folders inside, since I couldn't reproduce it exporting on postman format from restfox, but I created a postman collection with some embedded folders inside where I could reproduce the issue.

Here is the sample postman collection:
[Sample Postman collection.postman_collection.json](https://github.com/user-attachments/files/18123006/Sample.Postman.collection.postman_collection.json)

**Comment by flawiddsouza** [comment]
Hi @Dokkaltek, I tested with your given postman collection on a file workspace and was unable to reproduce the issue:

https://github.com/user-attachments/assets/5b069d1b-bcda-4099-994b-13fac88785c6

Can you give me the exact steps or a recording of the issue you're facing?

**Comment by Dokkaltek** [comment]
I recorded the issue. It seems to not allow renaming the root folder of the imported collection, but it doesn't have any issue with renaming child folders inside that root folder.

It also won't allow you to move the folder to any other folder you may have created later in the workspace.

I tested on 2 machines, and it happens on both for me, both on version 0.32

![image](https://github.com/user-attachments/assets/0216cf2f-e890-4779-9fc2-d72d7e894efe)

https://github.com/user-attachments/assets/71d7ff40-dfab-4769-bdba-f52418c84e0d

**Comment by flawiddsouza** [comment]
"EPERM: operation not permitted" is a file permission issue. Also I see that you're on windows. I'll check on windows once as well. The video I shared was from a linux system.

Can you try creating the workspace in a different folder, possibly a different drive? I assume the issue is specific to your system. if you have a secondary system, do test it once in that as well.

Basically what the error is saying is that Restfox doesn't have permission to rename the folder you created. The reason it can rename the folders inside that folder is because those folders are created by Restfox and the permissions will be accordingly different.

**Comment by flawiddsouza** [comment]
"EPERM: operation not permitted" is a file permission issue. Also I see that you're on windows. I'll check on windows once as well. The video I shared was from a linux system.

Can you try creating the workspace in a different folder, possibly a different drive? I assume the issue is specific to your system. Maybe that specific onedrive folder.

Since you've tested on two systems, just want to confirm, if you were creating the workspace in the onedrive folder in the 2nd system as well?

**Comment by Dokkaltek** [comment]
I tested outside the onedrive folder on both systems, both directly on the user profile folder and on a folder directly on C:/, but had the same result.

I also tested creating a new folder directly on %appdata%/Restfox, where the configuration files of Restfox are (where it should have permissions), and it gave the same error.

I also tested running restfox as admin, but it didn't make any difference. I also made sure to not add spaces on the folders just in case, but the error it gave was the same.

**Comment by Dokkaltek** [comment]
Oddly enough it does create the folders of the workspace where you tell it to, and you can create other folders like normal, but it won't allow you to rename the damaged postman folder nor move it on a folder you create manually on restfox later.

**Comment by Dokkaltek** [comment]
After some more testing it seems like it doesn't happen specifically to postman imports, but it happens to folders created directly on restfox as far as it has subfolders in it.

I found some stackoverflow issue that might be relevant:
https://stackoverflow.com/questions/64964891/node-js-fs-module-rename-directory-that-has-subdirectories-eperm-exdev

**Comment by flawiddsouza** [comment]
> After some more testing it seems like it doesn't happen specifically to postman imports, but it happens to folders created directly on restfox as far as it has subfolders in it.

After what you said, I thought it was weird that it was happening only for postman imports. Seems like it's a general issue on windows. Folders with sub folders are the culprits.

I'm using fs.renameSync as that seemed like the correct thing to rename a folder. This works fine on macOS and linux. But not on windows sadly it seems.

Thanks for the thorough testing. Also thanks for the link. Should help.

**Comment by flawiddsouza** [comment]
I found this: https://github.com/paulmillr/chokidar/issues/1380. We're using chokidar to watch files and keep them updated in the application. I think we're hitting this issue rather than a windows bug. I mean it is a bug specific to windows but it is being caused by chokidar. This seems like it will be tricky to fix but it needs to be fixed.

**Comment by Dokkaltek** [comment]
Maybe as suggested on the stackoverflow issue possible solution it would be better to just create a new folder with the name changed, move everything from the old folder to the new one recursively and then delete the old folder. That way the chokidar issue wouldn't have the underlying fs issue that comes from node for renaming folders with subfolders.

Since on Linux and Mac it works as it should, checking the running OS to perform the workaround rename in case it's windows, and otherwise keep using the old fs.renameSync method.

So something as suggested of:

``` js
rename(path: string, newPath: string) {
    if (fs.existsSync(newPath)) {
      throw new Error('Already exists');
    }
    
    if (fs.lstatSync(path).isDirectory()) {
      fs.copySync(path, newPath);
      fs.rmdirSync(path, { recursive: true });
    } else if (fs.lstatSync(path).isFile()) {
      fs.renameSync(path, newPath);
    }
  }
```

**Comment by flawiddsouza** [comment]
Hi @Dokkaltek, new release with the above fix: https://github.com/flawiddsouza/Restfox/releases/tag/v0.33.0. Can you check and let me know if this issue has been fixed correctly?

**Comment by Izheil** [comment]
Everything seems to be working correctly now, thank you for the fix!

**Comment by Dokkaltek** [comment]
Everything seems to be working now, thanks!
