### ISSUE TITLE
Bug: When autocompleting an environment variable, closing braces are added even when they are not needed

### ISSUE THREAD

**Issue by Greenheart** [flawiddsouza/Restfox#297]
First of all, thanks for this amazing tool! Restfox is exactly what I need, and I love the minimalistic and offline-first approach :blush:

A minor bug/annoyance is that replacing an environment variable always ends up adding two extra closing braces, even if they are not needed. Perhaps the surrounding text in the editor could be scanned to see if the closing braces are needed or not.

https://github.com/user-attachments/assets/e8841505-370b-42f4-b630-248a54d72a3b

Severity: This can pretty easily be worked around, but it would be a nice UX improvement.

**Comment by flawiddsouza** [comment]
I've noticed this happen before. I'll see what I can do.

I'm glad you find the application useful 😊

**Comment by flawiddsouza** [comment]
Hi @Greenheart, I've pushed a fix for the above. You can test it at: https://restfox.dev and let me know if there are any issues still remaining.

**Comment by Greenheart** [comment]
It works perfectly - thank you! :pray:
