### ISSUE TITLE
Beautify JSON does not work if unquoted variables are used in the Body

### ISSUE THREAD

**Issue by jaybz** [flawiddsouza/Restfox#3]
Beautify JSON does not work with the following JSON Body for example:

```
{
    "requestObject": {
        "requestType": "requestType1","targetId": {{ TestTargetId }}
    }
}
```

Enclosing {{ TestTargetId }} in quotes will allow Beautify to work. This workaround is fine for endpoints that do not distinguish between numeric and string types, but not so for endpoints that do have behavioral differences when numeric values are passed as a string vs numeric type.

**Comment by flawiddsouza** [comment]
This is a really good catch. I'll see what I can do to fix this. Thanks for the bug report.

**Comment by jaybz** [comment]
This is related but not exactly the same and could be harder to deal with, but if you use unquoted variables to add whole JSON objects (which means you can't work around it using quotes), the same issue occurs. For example:

```
{
    "requestObject": {
        "requestType": "requestType1","targetId": 12345
    }, 
    {{ AnotherObject }}
}
```

**Comment by flawiddsouza** [comment]
Yes, this would definitely be harder to deal with. I'll see what to do when I pick this up.

**Comment by flawiddsouza** [comment]
Yes, this would definitely be harder to deal with. I'll see what to do when I pick this up.

**Comment by flawiddsouza** [comment]
@jaybz You can test once now. Both your examples should get formatted.

**Comment by jaybz** [comment]
> @jaybz You can test once now. Both your examples should get formatted.

I've confirmed that both cases (and a few others) gets formatted properly. Nice work!
