### ISSUE TITLE
Resending a successful request (which should fail now) hangs in "loading" step

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#301]
I have a small server with OAuth2 authentication. In Restfox, I first request a token and copy it to another request (yes, there is a built in flow now ;-)). 
The issue happens if I first sent a valid request. Then I restart the server, which discards the old OAuth token.

When resending the previously successful request with the old (and invalid) token, Restfox gets stuck in the "Loading" animation:
![restfox](https://github.com/user-attachments/assets/20df600e-e3bf-4e0e-9099-34e2e227d2f8)

After restarting restfox and resending the request, I receive the expected error message:
![token_invalid](https://github.com/user-attachments/assets/2f62cb72-5259-43d7-a80d-20156cd50b68)

So, I hope it is not a problem of the server side and my OAuth2 implementation (using .NET8 and [https://github.com/openiddict/openiddict-core/](https://github.com/openiddict/openiddict-core/) ).

Other error conditions (e.g. "400 bad request" due to invalid parameters) are handled as expected.

**Comment by flawiddsouza** [comment]
I tried reproducing the above using a nodejs server with a similar flow but I was unable to recreate it.

Can you try this:
1) create token
2) send successful request using token
3) restart restfox
4) restart server
5) send request -> find out if it gets stuck in loading or resolves successfully?

Did you also try cancelling (Click "Cancel Request" below the loader) and resending the request without restarting restfox? Does that work?

I want to understand if restarting is actually fixing the issue or something else is happening there.

**Comment by flawiddsouza** [comment]
I was able to reproduce the issue using these steps:
1. npm start packages/test-api-http2
2. disable ssl checking in restfox
3. send request to https://localhost:8443
4. stop server
5. send request again - you'll now see the infinite loader
6. start server again
7. cancel the loader using "cancel request"
8. send request again - this will succeed

Issue was in the package we use to send http requests. You do not need to restart restfox to fix the issue. Click on cancel request and send the request again. It should work correctly. Will be releasing a new version of the application soon. Thanks for reporting the bug.

**Comment by flawiddsouza** [comment]
New version released: https://github.com/flawiddsouza/Restfox/releases/tag/v0.34.0. Please check and let me know if it's fixed.

**Comment by WolfgangHG** [comment]
@flawiddsouza It works now, many thanks! Glad you could make sense of my error description ;-).
