### ISSUE TITLE
Add search feature to response preview pane

### ISSUE THREAD

**Issue by jaybz** [flawiddsouza/Restfox#36]
The response preview pane is not quite searchable with browser's built-in find feature. I tried this in Firefox and Chrome, and although they behave somewhat differently, I can't fully search responses that are long using CTRL+F on either browser. I'm guessing this is because Restfox lazy loads the contents of the preview pane. The lazy loading behavior helps Restfox be fast and lightweight so I wouldn't want to change that behavior just to "fix" the browser's built-in find, but it would be nice if Restfox provided a way to search the response without changing the lazy loading behavior. This can be worked around easily by copy-pasting the response to a text editor so this is just a nice-to-have feature though.

**Comment by flawiddsouza** [comment]
@jaybz This is now implemented:

![image](https://user-images.githubusercontent.com/10164500/208097525-6fc51c17-1da7-4b3f-accd-fb48c61a4126.png)

Keeping the cursor inside the response panel, you can press <kbd>Ctrl + F</kbd> and it will trigger this search instead of the browser's.
