### ISSUE TITLE
Unexpected non-whitespace character after JSON at position...

### ISSUE THREAD

**Issue by cezaryece** [flawiddsouza/Restfox#37]
When I try to setup enviroment variable I got error like in topic
I just try to set 
"host" : "http://localhost"

**Comment by cezaryece** [comment]
In case it can do matter:
Ubuntu Studio 22.10 (KDE)
I have also strange problem that any my request (with full address) give me:
Error: Request failed
Possible causes for this error....

And - copy button in response window dosnt copy anything.

**Comment by flawiddsouza** [comment]
Hi @cezaryece, environment needs to a json string, so
```
host" : "http://localhost"`
```
should be
```
{
    "host" : "http://localhost/"
}
```
That should get rid of the environment variable error.

Any OS should be fine. How are you using Restfox? Through a browser? If so, can I know which browser it is? And what is the url you're accessing? If you're on a browser, if it's not localhost and the url does not have CORS, you have to install a browser extension to bypass CORS.

**Comment by flawiddsouza** [comment]
Hi @cezaryece, environment needs to be a json string, so
```
host" : "http://localhost"`
```
should be
```
{
    "host" : "http://localhost/"
}
```
That should get rid of the environment variable error.

Any OS should be fine. How are you using Restfox? Through a browser? If so, can I know which browser it is? And what is the url you're accessing? If you're on a browser, if it's not localhost and the url does not have CORS, you have to install a browser extension to bypass CORS.

**Comment by cezaryece** [comment]
No, I install Restfox 0.0.7 from Snap
My url is exactly http://localhost:3000/login
It is endpoint created by localy running Cutelyst server and it is working well in Postman and other web requests clients.

**Comment by cezaryece** [comment]
In fact I wonder if there should be something add to header part, which now seems looking empty.

**Comment by flawiddsouza** [comment]
> No, I install Restfox 0.0.7 from Snap My url is exactly http://localhost:3000/login It is endpoint created by localy running Cutelyst server and it is working well in Postman and other web requests clients.

Then what I mentioned shouldn't be an issue for you. This is very odd. I haven't heard of a request failing in Restfox while not failing in Postman and other clients, so there should be something going on.

> In fact I wonder if there should be something add to header part, which now seems looking empty.

As you mentioned, this could be the issue. What body type is your request? Restfox usually adds the Content-Type header by default if you select a body type. Do make sure your body type isn't set to "No Body".

By the way, is http://localhost:3000/login a GET or a POST?

**Comment by cezaryece** [comment]
OK, I found source of problem.
I import collection from Postman. In imported requests there is no header content at all.
When I recreate login request Restfox add Content-type header and this start to work.
So, problem is with importing headers from Postman or at least recreating required headers.

**Comment by flawiddsouza** [comment]
Postman does a bit of magic with its headers to make stuff a bit easier for its users. There are two types of headers in it. One that are generated by postman and others are the ones you add. The auto generated headers are not stored inside the request. Hence they will be missing in the import.

This magic behavior can cause confusion during implementation as the API that was working in Postman might not work during implementation due to a missing header that you didn't know was required. Restfox does not add any additional headers to keep things simple and straightforward. You send what you see. But I might add this behavior if enough people ask for it.

By the way, were you able to fix the issue with the environment?

**Comment by cezaryece** [comment]
Yes, now I can set up environment variable, THX for tip.
BTW I think this tip could appear somewhere (like placeholder text), so no one will in doubt like me.

Back to import headers - IMHO you could add option (checkbox for example) to generate headers while importing collection or action in menu for it after import is done.
