### ISSUE TITLE
Does this app have graphql support?

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [flawiddsouza/Restfox#39]

**Comment by flawiddsouza** [comment]
Hi @A-childs-encyclopedia, graphql is supported. Here's how to use a graphql API:
<kbd>![image](https://user-images.githubusercontent.com/10164500/215017071-9b5ad48d-72f4-4554-89d8-38126c0843bf.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/10164500/215017088-57144439-2239-49be-bc20-21f2a44d402e.png)</kbd>

Hope you find that useful.

**Comment by flawiddsouza** [comment]
Hi @A-childs-encyclopedia, graphql is supported. Here's how to use a graphql API:

<kbd>![image](https://user-images.githubusercontent.com/10164500/215017071-9b5ad48d-72f4-4554-89d8-38126c0843bf.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/10164500/215017088-57144439-2239-49be-bc20-21f2a44d402e.png)</kbd>

Hope you find that useful.

**Comment by A-childs-encyclopedia** [comment]
Tysm!
