### ISSUE TITLE
CTRL+Left and CTRL+Right are not handled by focused text input boxes

### ISSUE THREAD

**Issue by jaybz** [flawiddsouza/Restfox#4]
When text input boxes are focused, CTRL+Left and CTRL+Right switches tabs instead of moving 1 word to the left/right. I've observed this behavior in the Request URL field, JSON/Plain Text Body, and the request rename input boxes (both via double-click or right-click->properties)

**Comment by flawiddsouza** [comment]
Oh no. Looks like I've broken the default behavior with the tab switching shortcuts. Will fix this soon. Thanks for the bug report.
