### ISSUE TITLE
Import CURL request

### ISSUE THREAD

**Issue by NitinStar** [flawiddsouza/Restfox#44]
Hi, 
I am not able to import CURL request in REST fox. is there any option?

**Comment by flawiddsouza** [comment]
Hi @NitinStar, this feature does not exist of yet but I'm planning to implement it soon. Will update here once it's done.

**Comment by rodorgas** [comment]
Hi @flawiddsouza, is there any progress on this feature? This is fundamental to my workflow and I may find some time to build a PR if it's OK to you.

**Comment by flawiddsouza** [comment]
Been meaning to get to this. Finally implemented it: https://github.com/flawiddsouza/Restfox/commit/d96837c0382abee64bfd2a2b0abe910f90cc8e47. You can now import a curl command by pasting into the address bar of the request. Hope you find this useful.

The latest commit is deployed to https://restfox.dev. I'll release a new version for desktop some time in the next week.
