### ISSUE TITLE
Local edit/read file

### ISSUE THREAD

**Issue by ForMyFreedom** [flawiddsouza/Restfox#47]
It would be awesome if restfox instead of using the import/export boring feature, to set some way to make the changes be actual read and edit in a local file.
This makes the "Giting" a lot more easy...

**Comment by flawiddsouza** [comment]
On browser, this could be done with https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API. But it's not stable enough yet. Current blocker is that it'll keep asking the user for permission to read/write files every time the app is opened, which is a no go for me. We'll have to wait and see.

**Comment by flawiddsouza** [comment]
File workspaces are now implemented and released as of https://github.com/flawiddsouza/Restfox/releases/tag/v0.7.0.
