### ISSUE TITLE
Wrong Content-Type header

### ISSUE THREAD

**Issue by vaidis** [flawiddsouza/Restfox#48]
on POST method, I set the Body to 'Form URL Encoded' and I add the header "Content-Type" : "application/x-www-form-urlencoded" but the restfox sends header "Content-Type" : "text/plain;charset=UTF-8" which is wrong

Version: v0.0.8
Installation: Using web-standalone
node: v18.16.1
os: Rocky Linux release 9.2

**Comment by flawiddsouza** [comment]
Hi @anarckk, this issue should be fixed with my latest commit: https://github.com/flawiddsouza/Restfox/commit/a14216bcd85b681a99c572d41be6ada87be4252d. Will be pushing a docker image update soon.
