### ISSUE TITLE
Save binary response as file

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#49]
First of all: this is great tool! Postman forced me to switch as they discontinue the Scratchpad. Restfox works like a charm ;-). 

I miss one Postman feature: in my API, I have an endpoint that returns binary data (e.g. an image). Restfox displays the raw data.

Could you add the postman feature to save it as file? Here is Postman screenshot:
![postman_save_response](https://github.com/flawiddsouza/Restfox/assets/138049/8325eef8-9a57-4860-94eb-0e2336fcd34f)

My service also sets the "Content-Disposition" header with a filename (it is generated by C# code):
`attachment; filename=dispositionservicerest_restfox_gettoken1_net6.png; filename*=UTF-8''dispositionservicerest_restfox_gettoken1_net6.png`
This filename could be defaulted to the "Save as" dialog.

Postman also supports "Save to file" for JSON responses, where a filename "response.json" is defaulted.

**Comment by flawiddsouza** [comment]
Hi @WolfgangHG, this is now implemented.

Feature is live at https://restfox.dev and will be released on desktop in a few weeks.

Caveats:
If using Restfox through https://restfox.dev without installing the companion CORS helper (<a href="https://chrome.google.com/webstore/detail/pgoncladmcclnmilkbnmmbldcihdgfnf">Chrome</a> | <a href="https://addons.mozilla.org/en-US/firefox/addon/restfox-cors-helper/">Firefox</a>). Your request needs to have this header:
```
Access-Control-Expose-Headers: Content-Disposition
```
For the application to access the Content-Disposition header.

Hope you find this useful.

**Comment by WolfgangHG** [comment]
Great, thanks!
