### ISSUE TITLE
Support for setting environment variables in plugins

### ISSUE THREAD

**Issue by jaybz** [flawiddsouza/Restfox#5]
An example use case would be for authentication schemes where a token is returned as part of the request. The same token then has to be included in every header for subsequent requests until the token expires.

Based on my own use cases, setting environment variables temporarily works. By temporary, I mean values only persist in the current "session" but not when you close the browser window and re-open it. There may be use cases that need the values to persist across sessions though.

I am trying to find a workaround for my use case by using an object within the plug-in's scope that is persisted across requests, but I haven't found such an object yet.

**Comment by flawiddsouza** [comment]
Another feature I've wanted to implement for a while now. Just haven't had the time. Will definitely be in my todo.

**Comment by flawiddsouza** [comment]
Added two plugin methods that will allow you to set environment variables for the workspace:
![image](https://user-images.githubusercontent.com/10164500/198820463-0a6ed604-1579-4ce6-88f9-6e23f23dab2d.png)
