### ISSUE TITLE
Preview Request URL and Auto Add Path and Query Parameters to Query Tab When In path.

### ISSUE THREAD

**Issue by freddyyeddy** [flawiddsouza/Restfox#50]
Im trying to switch from Postman And would love to see what the URL generated would look like before sending a request. I would also prefer if query and path parameters would auto generate if input into path. This would fall in line with basic POST man functionality.

**Comment by azvyae** [comment]
You may wanna check this out #115

**Comment by freddyyeddy** [comment]
This one does seem to be missing the ask of this feature request. I'm
looking specifically for a preview. Before sending the request. This
ensures that the url is sanely generated before I sent a request to the
server. Just like in postman.

**Comment by flawiddsouza** [comment]
Hey @freddyyeddy, just to update. I've introduced full sync between query params in url and the items in the query tab in this release: https://github.com/flawiddsouza/Restfox/releases/tag/v0.8.0. Earlier there was partial and incomplete syncing. So your url should now reflect the request that is actually sent.

Path parameters are not synced as of now. This should be doable. Probably in the next release.

**Comment by flawiddsouza** [comment]
Path parameters syncing & url preview is now implemented and available in https://github.com/flawiddsouza/Restfox/releases/tag/v0.14.0.

![image](https://github.com/flawiddsouza/Restfox/assets/10164500/2d254369-c8bb-4173-a8fa-382e8b4d168f)

**Comment by freddyyeddy** [comment]
Sorry it took so long to respond. Yeah this feature is working awesome. Now I can sanity check the rendered URL before I send it. Thank you.
