### ISSUE TITLE
Environment Coloration

### ISSUE THREAD

**Issue by freddyyeddy** [flawiddsouza/Restfox#52]
The Environment Dropdown is easily Missed at first glance. I suggest implementing a simple Coloration of the Menu bar based on Environment chosen. This can be as simple as custom hex coloration, or randomly assigned colors on creation of an environment. So it is easy at first glance to determine the environment you are in.

**Comment by scott-prive** [comment]
+1, it is easy to miss.

Alternatively it might be worth drafting a "how to" document or video and attach to this issue. 
Even if the Theme doesn't support this goal, knowing where to set this in the UI code might encourage a community PR.

**Comment by justin-caldicott** [comment]
I wonder if the placement/organization of the buttons affect this. Perhaps some of these would be better located in the settings dialog to keep the main screen more minimal for things that are regularly changed.

**Comment by justin-caldicott** [comment]
Just to add, I love the colouration idea. I recently started using the Outlook app on Mac and find the way it uses colour to identify the "profile" you're looking at really nice.
