### ISSUE TITLE
Postman Import

### ISSUE THREAD

**Issue by yeikel** [flawiddsouza/Restfox#53]
It would be ideal to have a feature to import existing postman collections and environments

**Comment by sprive** [comment]
Postman import is listed as a feature... from HN announcement:
      _- Import collections exported from Postman and Insomnia_
- https://news.ycombinator.com/item?id=33287137

Restfox gives me "Invalid import file given: " when I try importing any exported Collection from Postman 10.17.3.
In somewhat urgent need of a workaround if one exists. 

Postman had been simply getting annoying, before. NOW Postman are eliminating ScratchPad/offline mode, and doing so force all users to sync their Environment data, their private API keys, onto Postman's servers (data compliance be damned).

**Comment by sprive** [comment]
@yeikel "Postman import" exists, and seems to work after import.   I just briefly tested it (everything looks there, but the collection is not tested yet, I am just getting started..). 

Be sure that in the Import dialog, you select "Postman" as the type to import.

**Comment by sprive** [comment]
Just a thank you to @flawiddsouza.   

Be aware that a "lot" more people will be trying out Restfox, because **Postman are going cloud-only** (ending "ScratchPad" offline use). THAT means Postman users will unknowingly upload their company's private API keys (Environments).

**Comment by flawiddsouza** [comment]
As @sprive mentioned, Import already has an option to import from Postman:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/f89900f0-4b9c-434d-be9d-298671dfe4bf)
Closing this issue for now. If anyone faces an issue with postman import, please create a new issue detailing the problem.
