### ISSUE TITLE
Only one "body" content saved on export when many exist

### ISSUE THREAD

**Issue by janzheng** [flawiddsouza/Restfox#57]
Problem:

If you create a new request, fill in `multipart/form-data` then switch to `application/json` and fill in some JSON, the system will only export  the `multipart/form-data` but not the `application/json` data in the body

Expected:

I think it's not clear that you have to delete all `multipart/form-data` when you switch to another mode like `application/json` or any changes will be unsaved (or not even stored between sessions). I think when users switch to a different mode, fill in data, then hit "run" it should be either expected that they're implicitly using this newly selected type. You could also warn people that switching mode will delete the previous mode (then delete that content from the `body`) — otherwise there's a mismatch between the UI and expected state vs. the system state.

**Comment by flawiddsouza** [comment]
Hi @janzheng, the latest data is always persisted when you switch from one type of body to another body. I'll post a video shortly demonstrating this.

The data related to multiple payloads are present in the export but the import only considers the active body type when importing the data. Hence, when imported, you won't see data of the other body types.

I did find a bug when exporting and importing the Multipart Form export. Export seems to have the data but when you import, no body is imported. Maybe this is what you're seeing.

**Comment by flawiddsouza** [comment]
Hi @janzheng, the latest data is always persisted when you switch from one type of body to another body. I'll post a video shortly demonstrating this.

The data related to multiple payloads are present in the export but the import only considers the active body type when importing the data. Hence, when imported, you won't see data of the other body types.

I did find a bug when exporting and importing the Multipart Form export. Export seems to have the data but when you import, no body is imported. Maybe this is what you're seeing.

You do not need to delete one body to update the new body.

**Comment by flawiddsouza** [comment]
Hi @janzheng, I've pushed a fix so all bodies that are exported get imported. And now the imported data will be the same as the export + state that you see in Restfox. Please try importing the file that you had previously exported. It already has all the bodies inside it. We just weren't importing it before. You should see your data. Hope this is okay. I do not want to introduce a popup / confirm asking the user to discard their other bodies since we do not discard them. But it seems like we discard them because the import code was not importing the full data stored in the export.

The fix is live on https://restfox.dev. It'll come to the desktop builds in maybe a month.

**Comment by janzheng** [comment]
I tested the new fix and the old issue is solved!

I think what was puzzling was I was having the issue of params or json text being dropped/discarded between browser sessions (I haven't used import yet). I think it's great the way it currently is that nothing's being discarded; I like fast switching between testing content types, but I thought there was a new feature that dropped text/params as you switched.

Thanks for all your hard work!

**Comment by flawiddsouza** [comment]
"I think what was puzzling was I was having the issue of params or json text being dropped/discarded between browser sessions" This is very odd. Data loss in this manner hasn't yet been reported by anyone else. I wonder if there's a bug we're not yet seeing. There's a chance for something like this to happen if your computer's primary disk storage runs out but that's very very rare. Let me know if you see something like this happen again. When it happens, just open your browser's devtools and see if there's some error in the console. We might be able to catch it.

**Comment by janzheng** [comment]
Thanks for the reply; I was unable to reproduce the error after the update
but I'll keep my eyes out. Thanks so much for an awesome tool; I use it
every day!
