### ISSUE TITLE
Allow plugins to expose output

### ISSUE THREAD

**Issue by fede-green** [flawiddsouza/Restfox#58]
First of all, thank you for this beautiful project!

Probably i haven't understood how to do this? I'm writing on a simple plugin that would store the value of a cookie after a user is successfully logged in. I created my plugin in the "Request" scope and enabled it, but i haven't understood where the `console.log()` output goes. Could you please help me understand?

thanks!

**Comment by flawiddsouza** [comment]
Hi, the output of console.log will be logged into the devtools console. If you're on the browser, that would be Ctrl + Shift + I. Same shortcut should work on the desktop version of Restfox as well.

Another way to open devtools on the desktop version is to hold <kbd>Alt</kbd>, which will bring up the top menu and then you can select toggle developer tools:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/953d429e-4faf-471e-ae32-c8a17c543df8)
