### ISSUE TITLE
Setting cookies

### ISSUE THREAD

**Issue by fede-green** [flawiddsouza/Restfox#59]
Hello, 

is there a way to set cookies? Maybe a plugin could be enabled to write cookie values?

thanks

**Comment by flawiddsouza** [comment]
Hi, currently there's no way to do this. I'll be looking into implementing this some time in the near future. But due to the limitation of the Fetch API, I don't think I'll be able to get it to work on the web (in the browser). But getting it to work on the desktop builds should be possible.

**Comment by flawiddsouza** [comment]
Hi. This is now implemented in [v0.3.0 (release)](https://github.com/flawiddsouza/Restfox/releases/tag/v0.3.0) for Electron (Desktop builds). You can now set the Cookie header by passing it in headers.
