### ISSUE TITLE
Support for using NodeJS libraries in plugins

### ISSUE THREAD

**Issue by jaybz** [flawiddsouza/Restfox#6]
The specific use case I have for this is for using CryptoJS to generate time-based HMAC keys for inclusion in authentication header(s). I'm not sure if there's a good way to implement this such that users can specify the libraries for themselves. But that would be preferable over having to build a set of NodeJS libraries into Resfox itself.

**Comment by flawiddsouza** [comment]
Hi, if you want to use NodeJS libraries in plugins, you can try something like I did here: https://github.com/flawiddsouza/restfox-plugin-juego-njs2-crypto-handler. You basically need to precompile your plugin. A little bit of a hassle but you can use any library you want.

**Comment by flawiddsouza** [comment]
Will be closing this issue for now. We'll explore this again if there's more interest or an issue with the suggested approach.
