### ISSUE TITLE
Unclear on the purpose of the tabs

### ISSUE THREAD

**Issue by justin-caldicott** [flawiddsouza/Restfox#60]
It seems a request can have at most one tab open. As such, when working with a few requests, the tabs appear to duplicate the function of the collection in the sidebar.

I imagine the benefit of this is that when you have a lot of requests in a collection, the tabs serve as a "working set" of requests. However for my use case, I find the duplication unhelpful.

(Great app btw, thank you)

**Comment by flawiddsouza** [comment]
I actually find the tabs really helpful. So do a lot of people who use the application. They allow you to just focus on the requests you want. Say you're working on a project. You don't want to keep searching for your request in a collection 100 when you only need 2 or 3 to do your work.

I will consider adding a toggle in the Settings to disable tabs for people who don't find this useful.

**Comment by sprive** [comment]
As a user, sometimes I want those tabs for the shortcut they provide.. but other times I want to get there for the history (response). And when I run out of space width, I close the less relevant tabs.

I can't yet articulate what's always perfect for me, but I can say there are different reasons/moods for wanting quick navigation to prior tabs/calls.
