### ISSUE TITLE
What is this external script for

### ISSUE THREAD

**Issue by MattBrooks95** [flawiddsouza/Restfox#62]
https://github.com/flawiddsouza/Restfox/blob/a14216bcd85b681a99c572d41be6ada87be4252d/packages/ui/index.html#L15

I was under the impression that this client was local only, but it pulls in a script from a third party.

**Comment by RiQuY** [comment]
That's for analytics, check this: https://umami.is/

**Comment by RiQuY** [comment]
@MattBrooks95 Btw, if you plan on using Bruno it has telemetry too: https://github.com/usebruno/bruno/blob/6facdfd66b74955d5082f83f69cd468c47dc5906/packages/bruno-app/src/providers/App/useTelemetry.js#L67

**Comment by flawiddsouza** [comment]
Hi @MattBrooks95, as @RiQuY said, it's for basic analytics. The app will work fine even without the analytics. This not a third party script but my self hosted instance of umami.is. There's no personal data collected but I'll be adding an option to turn off analytics in the settings for privacy conscious folk. There is no telemetry or action tracking. It only counts visitors to the app. It's not collecting any data related to urls or the data you transmit within the application. You can verify the requests and the data Restfox is sending to confirm this. Removing it seems like an extreme option as it's just used by me to see how many users the application has.

**Comment by MattBrooks95** [comment]
I see. Thank you for the transparency.
