### ISSUE TITLE
Graphql Schema

### ISSUE THREAD

**Issue by riezahughes** [flawiddsouza/Restfox#64]
I'm one of those abandoning ship from insomnia after years of love for the product. Coming here i can see Restfox covers almost everything i want. I did, however, find that while Graphql works great, i couldn't see a schema for the endpoints i used. This is one thing i find very handy. Am i overlooking it or is there no plan to have it at the moment?

**Comment by riezahughes** [comment]
I may give it a look myself :)

**Comment by flawiddsouza** [comment]
Now implemented in #191.

**Comment by riezahughes** [comment]
Thank you. I hoenstly ended up not having any time at all since then. So i really appreciate you taking time to do this!
