### ISSUE TITLE
Broken characters in export file dialog

### ISSUE THREAD

**Issue by severinsimmler** [flawiddsouza/Restfox#67]
When I click on the "Export" button, the characters seem to be broken:

![image](https://github.com/flawiddsouza/Restfox/assets/16133277/b09fe574-4f82-4967-9ffd-02651305c651)

I am on Ubuntu 23.04 and use:

```
$ snap info restfox
name:      restfox
summary:   Lightweight REST / HTTP Client
publisher: Artelin (flawid)
store-url: https://snapcraft.io/restfox
license:   unset
description: |
  A lightweight REST / HTTP Client based on Insomnia and Postman.
  
  Features:
  - Workspaces
  - Tabs
  - Nested Folders
  - Lots of context menus
  - Response history
  - Plugins
  - GraphQL support
  - Import collections exported from Postman and Insomnia
  - Simple user friendly interface
commands:
  - restfox
snap-id:      5F3RdI1tJO2Fj4oHj05gtSmT7osdZmDm
tracking:     latest/stable
refresh-date: today at 08:01 CEST
channels:
  latest/stable:    0.1.0 2023-09-28 (13) 80MB -
  latest/candidate: ↑                          
  latest/beta:      ↑                          
  latest/edge:      ↑                          
installed:          0.1.0            (13) 80MB -
```

**Comment by flawiddsouza** [comment]
Hi, I'm not sure if this a Restfox issue. Restfox just uses electron. This is your native ubuntu file selector. Can you try Ctrl + S in a browser you use. Does it also look like this?

**Comment by flawiddsouza** [comment]
I see. I'll try to give you a build with the latest electron version in a few days. You can check and let me know.

**Comment by paulwellnerbou** [comment]
I have the same issue, and until now it only happened with RestFox.

**Comment by flawiddsouza** [comment]
This seems like a recurring issue for ubuntu snap: https://github.com/electron-userland/electron-builder/issues/5217. Don't see any official fix except some commands. I'll try updating Restfox to the latest electron version. Hopefully that fixes it.

**Comment by flawiddsouza** [comment]
Hi @severinsimmler @paulwellnerbou, version 0.2.0 was released yesterday. It has the latest electron version. Let me know if the issue is fixed or still persists.

**Comment by severinsimmler** [comment]
Unfortunately it still looks like before with version 0.2.0.

**Comment by flawiddsouza** [comment]
Well, that's very sad to hear. I wish I could fix this but it seems very out of my control.

Can you try running these commands and restart Restfox and see if it helps?
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
It's mentioned here: https://github.com/electron-userland/electron-builder/issues/5217#issuecomment-700707564.

**Comment by severinsimmler** [comment]
Unfortunately this also does not work for me. However, closing this issue since it's apparently not a problem with Restfox, but with Snap and/or Gnome.
