### ISSUE TITLE
Copy request as curl

### ISSUE THREAD

**Issue by bbkane** [flawiddsouza/Restfox#68]
Hello! Is it possible to copy a request as a curl script? That would let me send interesting HTTP requests to my colleagues, some of whom are hardcore CLI junkies :) 

I could write a script to format the exported JSON into a curl call, but it would be much more convenient to have "Export > copy current request as curl" work (or perhaps a right click somewhere).

Anyway, thanks for restfox! I really like it so far!

**Comment by paulwellnerbou** [comment]
I definitely need this, too! Not only to share requests, but to process them further, for example with `jq`.

**Comment by flawiddsouza** [comment]
This is now implemented:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/cc00af3c-ee2b-4d29-a4e6-e33e361ba712)

Available at https://restfox.dev. Will be releasing new version for desktop builds soon.

**Comment by cj-scott-prive** [comment]
Hi. Based on your "available" comment, I tried https://restfox.dev/ but the option is missing for me:

The only difference in my usage is I am using {{vars}} defined in the website's Environment (just simple redacted test data). 

<img width="319" alt="Screenshot 2023-11-01 at 12 55 05 PM" src="https://github.com/flawiddsouza/Restfox/assets/83772757/2049fc8a-48f3-42a9-8f9a-85f3b8d67c73">

Really looking forward to this feature! :-)

**Comment by flawiddsouza** [comment]
Hi @cj-scott-prive, you should be seeing an update dialog at the bottom right of your screen like so:
<kbd>![image](https://github.com/flawiddsouza/Restfox/assets/10164500/c52eaa99-d75b-4331-895d-bea354d66b14)</kbd>
Click reload and the app should update. This is required, as PWAs are cached by the browser and need to updated every time something changes.

**Comment by cj-scott-prive** [comment]
Hi @flawiddsouza 
All set thank you!  

 FYI I never got the update dialog, even when I tried again, but "cached" mention helped... 
  I did a Shift-Reload of the page and then I could find the option in the expected place.

**Comment by cj-scott-prive** [comment]
Hmm. SO I tried this using {{vars}}, with vars defined in Environment, and I got a validation error with 4 possible causes.

During your formation of the cURL payload, are you by chance doing extended validation or talking to the endpoint URL?

I needed to redact one of my variables, for data-compliance reasons. 
Which means I populate a password var like so: `"partner_api_clientSecret": "REDACTED",`
That of course would error 4xx on the API, but I was planning on fixing the secret after I exported it.

**Comment by MariusSvaCujo** [comment]
Hi, @flawiddsouza this feature can be very useful. But currently if I am using environment variables as body parameters in the request and I try to use this Copy as Curl feature - it copies {{parameter name}} and not actual value from environment file.

**Comment by flawiddsouza** [comment]
> Hi, @flawiddsouza this feature can be very useful. But currently if I am using environment variables as body parameters in the request and I try to use this Copy as Curl feature - it copies {{parameter name}} and not actual value from environment file.

This is actually a bug. I'll be pushing a fix soon.

**Comment by flawiddsouza** [comment]
@MariusSvaCujo A fix has been pushed for the issue you have raised. Latest version is deployed and available at https://restfox.dev. A new release will be coming in a day or two.
