### ISSUE TITLE
Crash on fresh install

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [flawiddsouza/Restfox#69]
Im unsure how you will be able to replicate this. But I have just done a first time install, created a request, but when I click the auth dropdown, there are no options in it and the app freezes up completely.

**Comment by flawiddsouza** [comment]
Hi, can you let me know what OS you are on? Also it would be good to know which version of Restfox you tried to install.

Try pressing ctrl + shift + i after opening Restfox. If you've installed Restfox, this should bring up the devtools. In the console, there could be some errors. Try clicking on the auth dropdown and see if it prints any errors there. This would really help as I'm not able to reproduce any error on freshly installing the app on two different operating systems.

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Certainly.

Installed v0.1.0 via snap on Ubuntu 22.04.

I opened the dev tools sidebar and clicked the auth dropdown, but there was nothing there, and the app froze up again.

Sorry about that. Any other suggestions

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Just also noticed that the app freezes when I click on the "Import Into" field in the Import modal. Perhaps its every select field.

**Comment by flawiddsouza** [comment]
Sadly, I'm sure how to debug this since I cannot reproduce it. There also seems to be no error, which is not great. Will keep this open for now. I'll try installing freshly on a 22.04 ubuntu system to see if this happens there as well.

**Comment by flawiddsouza** [comment]
Hi @baronvertigovongrahamthesecondofsealand, is it possible for you to check the latest build and see if the issue still persists? There have been many fixes since then.

**Comment by flawiddsouza** [comment]
There was an input freezing bug that was fixed a while back, so that most likely fixed this. If not, please message here and I'll reopen this.
