### ISSUE TITLE
Allow enabling/disabling plugins on a per-workspace, per-folder, or per-request basis

### ISSUE THREAD

**Issue by jaybz** [flawiddsouza/Restfox#7]
For some of my use cases at least, plugins will need to be be specific to a project only and may break requests meant for other projects. The workaround for this is to code the plugin to allow disabling/enabling execution via environment variables, however, the per-workspace/folder/request feature is a far cleaner solution.

Alternatively, being able to create plugins specific to a workspace/folder/request might be better, but I'm not sure how that work work UI-wise. Maybe moving the plugins to the request tab and right-click menu or creating a separate plugin-like feature there might work.

edit: Sorry, lots of edits. I wasn't able to collect all my thoughts before posting this. Hopefully this is the last one.

**Comment by flawiddsouza** [comment]
This feature has been in my backlog for a while. Just haven't been able to the come up with the right ui for it. Once I think up something, I'll definitely implement it. Thanks for the feature suggestion.

**Comment by NeuronEnix** [comment]
## Is this do able?

can we have plugin moved to each request page
and also as well as in each collection page ( when it gets a page of its own like how the postman has )

![image](https://user-images.githubusercontent.com/50287102/202889866-28636da1-7585-4b7f-8fd2-6277a1f4c532.png)

<br/>
and under the plugin is it possible to have scripts as this? 

![image](https://user-images.githubusercontent.com/50287102/202889992-45a7c836-8d78-426f-a67d-5f309e2056c6.png)

or using `this`
![image](https://user-images.githubusercontent.com/50287102/202890018-aecbcf41-25f8-4f51-9ca5-89cdc06968d4.png)

and also feature to move the data around the collection
![image](https://user-images.githubusercontent.com/50287102/202890143-cc340489-66af-4fb7-90ec-a74ac4aa0139.png)

and also to listener or interceptors
![image](https://user-images.githubusercontent.com/50287102/202890288-f8a989a2-00a4-44ce-90a7-420231ac0a42.png)

**Comment by flawiddsouza** [comment]
I don't think we need to have a new set of functions or interceptors for a request specific plugin. We can just use the same functionality as the plugin:
![image](https://user-images.githubusercontent.com/10164500/202892778-e3584e7c-fcb9-4476-872d-7fe1637ce8ef.png)
We can definitely add more methods to the plugin system to accommodate more functionality.

"and also feature to move the data around the collection" Aren't environment variables already solving this use case? I think I'll need to understand more about this feature. 

I've thought of adding a Plugin tab in the request panel. But it often feels like the request panel already has too many tabs.

**Comment by flawiddsouza** [comment]
To support this feature request, what I've had in mind is that we'll be extending the plugin manager and adding a new column called Scope.

Available Scopes:
Global
Workspace

If a request is selected, these scopes will be added (these will be hidden if no request is selected / change when another request is selected):
Folder (Main Folder)
Folder (Main Folder -> Sub Folder)
Request (Main Folder -> Sub Folder -> My Request)

![image](https://user-images.githubusercontent.com/10164500/202893120-21ad8461-17c0-4a5b-a29b-689d04655ac7.png)

This is the existing Plugin Manager modal. The Scope  column will come before the Name column.

![image](https://user-images.githubusercontent.com/10164500/202893127-2923530a-fa73-4996-a579-2bda5c7252ab.png)

Scope dropdown will be added there and can also be changed at any time when editing the plugin. A plugin is never locked to a specific scope, so the scope can be re-assigned to any of the available scope options (global, workspace, request, request folder).

All existing plugins will default to global scope. And future plugins will default to Workspace scope. The user can then change the scope of the plugin while creating it.

**Comment by NeuronEnix** [comment]
""and also feature to move the data around the collection" Aren't environment variables already solving this use case? I think I'll need to understand more about this feature."

some time i need to use more than 1 user at a time parallelly
i assign some id to a variable ( probably collection scope )
![image](https://user-images.githubusercontent.com/50287102/202894736-fedb88d2-4d7a-46e1-a408-5b52771f70ff.png)

now i need to use the same data, to arrange the data correctly, to an id, which i might use in other place, each request components may share or have different id, and based on that, parent collection might run the scripts in different ways

![image](https://user-images.githubusercontent.com/50287102/202894955-8080ddd6-6c48-43d1-84f2-7218a071d457.png)

having these within the scope, make it easier to manage the data, if we make use of env it kinda feels like its getting crowded with data which gets added as and when i run the script, and data in env will just keep growing,

in the above pic im indeed setting them on env, during which i realized, the env is just getting more and more data in it, but if i move it to a collection scope variable, it'll makes it easier to manage.

this is just a personal preference that i have is, i see the env as some kind of constant configuration data, which keeps meta data on how the stuff should work...kind like `process.env` from js, doesnt feel right to add data to it as and when application runs

When env gets crowded...it kinda makes it harder to view and may be do some tiny modification.

And when i need to share my env data to someone, then i would have to manually check and erase the data that was added.

**Comment by NeuronEnix** [comment]
"To support this feature request, what I've had in mind is that we'll be extending the plugin manager and adding a new column called Scope."

im not sure how this would look like, i might need more pics to see how it may look like when we have many folders and requests...

for me, in my postman i would have these kinda structure
- proj1
  - module 1
     - module 1.1
        - req 1
        - req 2
        - req 3
      - module 1.2
         - req 1
         - req 2
  - module 2
      - req 1
      - req 2

and other projects with structured similarly
different scripts may be running on different module, sub module and request

having them all kept in scroll down, its difficult to manage

where as in postman its right where its required, because those plugin is specific to a request...or to that component only, having it along with a same tab will make easier to manage

**Comment by flawiddsouza** [comment]
> ""and also feature to move the data around the collection" Aren't environment variables already solving this use case? I think I'll need to understand more about this feature."
> 
> some time i need to use more than 1 user at a time parallelly i assign some id to a variable ( probably collection scope ) ![image](https://user-images.githubusercontent.com/50287102/202894736-fedb88d2-4d7a-46e1-a408-5b52771f70ff.png)
> 
> now i need to use the same data, to arrange the data correctly, to an id, which i might use in other place, each request components may share or have different id, and based on that, parent collection might run the scripts in different ways
> 
> ![image](https://user-images.githubusercontent.com/50287102/202894955-8080ddd6-6c48-43d1-84f2-7218a071d457.png)
> 
> having these within the scope, make it easier to manage the data, if we make use of env it kinda feels like its getting crowded with data which gets added as and when i run the script, and data in env will just keep growing,
> 
> in the above pic im indeed setting them on env, during which i realized, the env is just getting more and more data in it, but if i move it to a collection scope variable, it'll makes it easier to manage.
> 
> this is just a personal preference that i have is, i see the env as some kind of constant configuration data, which keeps meta data on how the stuff should work...kind like `process.env` from js, doesnt feel right to add data to it as and when application runs
> 
> When env gets crowded...it kinda makes it harder to view and may be do some tiny modification.
> 
> And when i need to share my env data to someone, then i would have to manually check and erase the data that was added.

I see. This is something like temporary session variables that get reset when you reopen the software. We can definitely add that to the plugin system. Variable scoping sounds good. But when a collection is inside another collection and so on, the nested scoping would be quite hard to implement and annoying to maintain without bugs.

**Comment by flawiddsouza** [comment]
> ""and also feature to move the data around the collection" Aren't environment variables already solving this use case? I think I'll need to understand more about this feature."
> 
> some time i need to use more than 1 user at a time parallelly i assign some id to a variable ( probably collection scope ) ![image](https://user-images.githubusercontent.com/50287102/202894736-fedb88d2-4d7a-46e1-a408-5b52771f70ff.png)
> 
> now i need to use the same data, to arrange the data correctly, to an id, which i might use in other place, each request components may share or have different id, and based on that, parent collection might run the scripts in different ways
> 
> ![image](https://user-images.githubusercontent.com/50287102/202894955-8080ddd6-6c48-43d1-84f2-7218a071d457.png)
> 
> having these within the scope, make it easier to manage the data, if we make use of env it kinda feels like its getting crowded with data which gets added as and when i run the script, and data in env will just keep growing,
> 
> in the above pic im indeed setting them on env, during which i realized, the env is just getting more and more data in it, but if i move it to a collection scope variable, it'll makes it easier to manage.
> 
> this is just a personal preference that i have is, i see the env as some kind of constant configuration data, which keeps meta data on how the stuff should work...kind like `process.env` from js, doesnt feel right to add data to it as and when application runs
> 
> When env gets crowded...it kinda makes it harder to view and may be do some tiny modification.
> 
> And when i need to share my env data to someone, then i would have to manually check and erase the data that was added.

I see. This is something like temporary session variables that get reset when you reopen the software. We can definitely add that to the plugin system. Variable scoping sounds good. But when a collection is inside another collection and so on, the nested scoping would be quite hard to implement and annoying to maintain without bugs.

I think you should create a new issue for this to track this feature request. We're getting side tracked here as this issue is related to having plugins for different scopes (workspace, folder and request).

**Comment by flawiddsouza** [comment]
> "To support this feature request, what I've had in mind is that we'll be extending the plugin manager and adding a new column called Scope."
> 
> im not sure how this would look like, i might need more pics to see how it may look like when we have many folders and requests...

So in the scope dropdown, you'll only see the request that is currently selected and its ancestors. The scope dropdown will never show all requests and folders. It will always be limited to showing the current request and its parent + ancenstors if any. So at most you'll see 4-5 items in the scope dropdown.

**Comment by flawiddsouza** [comment]
> "To support this feature request, what I've had in mind is that we'll be extending the plugin manager and adding a new column called Scope."
> 
> im not sure how this would look like, i might need more pics to see how it may look like when we have many folders and requests...



> "To support this feature request, what I've had in mind is that we'll be extending the plugin manager and adding a new column called Scope."
> 
> im not sure how this would look like, i might need more pics to see how it may look like when we have many folders and requests...
> 
> for me, in my postman i would have these kinda structure
> 
> * proj1
>   
>   * module 1
>     
>     * module 1.1
>       
>       * req 1
>       * req 2
>       * req 3
>     * module 1.2
>       
>       * req 1
>       * req 2
>   * module 2
>     
>     * req 1
>     * req 2
> 
> and other projects with structured similarly different scripts may be running on different module, sub module and request
> 
> having them all kept in scroll down, its difficult to manage
> 
> where as in postman its right where its required, because those plugin is specific to a request...or to that component only, having it along with a same tab will make easier to manage

So in the scope dropdown, you'll only see the request that is currently active and its ancestors. The scope dropdown will never show all requests and folders. It will always be limited to showing the current request and its parent + ancestors if any. So at most you'll see 4-5 items in the scope dropdown.

My goal with Restfox is to avoid taking it in the route that Postman went and keeping at as simple and minimal as possible. So I'd like to avoid directly copying the decisions that Postman made in its software into ours. But I'm open to alternate suggestions.

**Comment by flawiddsouza** [comment]
> "To support this feature request, what I've had in mind is that we'll be extending the plugin manager and adding a new column called Scope."
> 
> im not sure how this would look like, i might need more pics to see how it may look like when we have many folders and requests...
> 
> for me, in my postman i would have these kinda structure
> 
> * proj1
>   
>   * module 1
>     
>     * module 1.1
>       
>       * req 1
>       * req 2
>       * req 3
>     * module 1.2
>       
>       * req 1
>       * req 2
>   * module 2
>     
>     * req 1
>     * req 2
> 
> and other projects with structured similarly different scripts may be running on different module, sub module and request
> 
> having them all kept in scroll down, its difficult to manage
> 
> where as in postman its right where its required, because those plugin is specific to a request...or to that component only, having it along with a same tab will make easier to manage

So in the scope dropdown, you'll only see the request that is currently active and its ancestors. The scope dropdown will never show all requests and folders. It will always be limited to showing the current request and its parent + ancestors if any. So at most you'll see 4-5 items in the scope dropdown.

My goal with Restfox is to avoid taking it in the route that Postman went and keeping at as simple and minimal as possible. So I'd like to avoid directly copying the decisions that Postman made in its software into ours. But I'm open to alternate suggestions.

**Comment by flawiddsouza** [comment]
@jaybz This feature is now implemented:

## Global and Per Workspace:

![image](https://user-images.githubusercontent.com/10164500/204205468-28235b00-f0c2-4a69-8dd0-478bb3ee272e.png)

![image](https://user-images.githubusercontent.com/10164500/204206351-e6d67cac-fb48-420e-ba71-ea5376669c91.png)

## Per Folder

<kbd>![image](https://user-images.githubusercontent.com/10164500/204205985-5fe0f456-00c3-4227-aa28-6bf631531601.png)</kbd>

![image](https://user-images.githubusercontent.com/10164500/204207055-8f4c30ef-aa09-491f-ad13-0b19f0a3e820.png)

## Per Request

<kbd>![image](https://user-images.githubusercontent.com/10164500/204205670-e8a2fcae-1de3-4d12-98ee-09b31c528cab.png)</kbd>

![image](https://user-images.githubusercontent.com/10164500/204206877-1c4d33cd-e4d0-4c5b-bbfb-dd7502cebee3.png)
