### ISSUE TITLE
Publish on flathub

### ISSUE THREAD

**Issue by dreamyukii** [flawiddsouza/Restfox#71]
it would be nice to have this apps on flathub

**Comment by x80486** [comment]
If you are still interested, I can (try to) [build the application](https://github.com/x80486/flathub/tree/dev.restfox.app) and publish it to Flathub.

You wouldn't need to build the Flatpak from this repository, as Flathub streamlines that process almost automatically, and the updates will be published whenever a new release is available while using their automated checking system.

However, I want to note that I won't be able to _actively_ maintain the Flatpak release, as I am already committed to several other projects — but I will be available to contribute and assist with any questions or issues that may arise. At any rate, it's best for the official maintainers to take charge of this, and also _verify_ the published application at some point.

**Comment by flawiddsouza** [comment]
Hey @x80486, thanks for the help. Just getting it built and published to flathub would be a huge help. You don't have to worry about maintaining and testing it. I'll take care of that.

**Comment by x80486** [comment]
Great, so let's move forward! It would be great to fix some things before sending the pull request. For instance:

- What's the [correct ID](https://docs.flatpak.org/en/latest/conventions.html) for the application?
- Could you publish the next release with an SVG icon instead?

Lastly, not required but highly desired, is to have all those assets to follow the application's ID scheme, so the Flatpak manifest becomes less convoluted — and anyways it's the standard if you were to follow the [Freedesktop AppStream](https://www.freedesktop.org/software/appstream/docs/) specification.

**Comment by flawiddsouza** [comment]
> What's the correct ID for the application?

`dev.restfox.app` looks correct.

> Could you publish the next release with an SVG icon instead?

I've pushed the svg version of icon: https://github.com/flawiddsouza/Restfox/commit/86df520dbd1e10604250570b33412a828e72c6a3. Do I need to change anything in the electron config?

> Lastly, not required but highly desired, is to have all those assets to follow the application's ID scheme, so the Flatpak manifest becomes less convoluted

I'm publishing to different platforms, so changing all this just for flathub seems a bit extreme. But you mention it's not required. If there's something important, I will change it as requested.

**Comment by x80486** [comment]
Great! I will download the SVG icon from the repository for the time being. If you plan to include it as part of the release, it can be used instead.

**Comment by x80486** [comment]
Found out that `.app` is not a proper application name, so I guess the application ID should be different. How about `dev.restfox.RestFox` or `dev.restfox.Restfox`?

**Comment by flawiddsouza** [comment]
`dev.restfox.Restfox` sounds good to me.

Looks like the icons on the dashboard were broken in the last build. I've fixed it and released a new build: https://github.com/flawiddsouza/Restfox/releases/tag/v0.29.0.

The warnings are from electron on not being able to connect to dbus I think. They are not related to the application, so we can ignore them.

**Comment by x80486** [comment]
Application [submitted](https://github.com/flathub/flathub/pull/5746) to Flathub.

**Comment by flawiddsouza** [comment]
Hi @x80486, sorry to bother you.

![image](https://github.com/user-attachments/assets/1309e732-e7b8-431b-8c41-f254b7ccfdea)

I didn't understand what I need to do here. As .debs are automatically generated by electron forge, do you know what I need to do here? Is this a requirement for the application to be published to flathub? The process seems so cumbersome compared to my experience submitting the application to other package managers.

**Comment by x80486** [comment]
This is a recommendation only — or I would take it as such.

The ask is to include the current file I generated: `dev.restfox.Restfox.metainfo.xml` into this repository so it _becomes part_ the Restfox release — think of it as some sort of release notes, or changelog, but it's much more than that.

The not-so-straightforward part is that, as far as I know, Electron does not provide an automated way to update this file (read: the `releases` section for the most part) with the built-in toolchain. Of course, it could be done with some other tools, but you would need to build/modify all of that, hence my suggestion to take this action item and complete it later.

The same goes to build the application using sources — it can be done later.

But indeed, pretty much all GNU/Linux applications should bundle this file.

The Flatpak application is ready to go. It's just a matter of Flathub to finally merge that pull request — they might be reviewing some other applications.

**Comment by flawiddsouza** [comment]
Alright, that's actually helpful. Thank you.

**Comment by flawiddsouza** [comment]
App is now available on Flathub: https://flathub.org/apps/dev.restfox.Restfox. Thanks @x80486!
