### ISSUE TITLE
Feature request: scripting

### ISSUE THREAD

**Issue by JWSemmelink** [flawiddsouza/Restfox#76]
A scripting feature in Restfox will be very helpful. 

Here is one example how scripting might be useful:

User makes a call to log in to a site. The site responds with json, containing for example a tag: "JwtToken"="XXXYYZZZ". The script (see the "test" tab in Postman) can be programmed to scan the response on this specific call, and to populate a variable in the environment. 
```
var jsonData = JSON.parse(responseBody);
pm.environment.set("jwt-token",jsonData["JwtToken"]);
```
So the following calls can pull the {{jwt-token}} variable from the environment without a need that the user set it manually.  

Above is just one example of using scripting - there are other use cases as well, such as testing.
https://learning.postman.com/docs/writing-scripts/script-references/test-examples/

**Comment by flawiddsouza** [comment]
Hi @JWSemmelink, this feature is already present in Restfox. It's called Plugins. Please watch this video to see how it works: https://www.youtube.com/watch?v=3cOQPm43Wus.

**Comment by Mik39907** [comment]
I am not able to do this now im trying exactly like the video
difference is only I have already multiple variables in my environment
