### ISSUE TITLE
Export an API call to Retrofit/OkHttp in Kotlin

### ISSUE THREAD

**Issue by mariusCujo** [flawiddsouza/Restfox#79]
Plugin needed

**Comment by flawiddsouza** [comment]
This is now implemented:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/f9c22236-30d9-440b-ad36-d03c20020776)
![2024-01-17_11-56](https://github.com/flawiddsouza/Restfox/assets/10164500/1fcb0989-d6ce-493a-a0f4-dfdcacf1305a)
