### ISSUE TITLE
Request: user-agent headers

### ISSUE THREAD

**Issue by lazmo88** [flawiddsouza/Restfox#82]
Allow modifying user-agent headers, as of now restfox always forces it's own UA even if you specify custom user-agent header:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Restfox/0.2.1 Chrome/118.0.5993.89 Electron/27.0.2 Safari/537.36`

**Comment by flawiddsouza** [comment]
Hi. This is now implemented in https://github.com/flawiddsouza/Restfox/releases/tag/v0.3.0. You can now override the user agent header by passing it in headers.
