### ISSUE TITLE
Connection to "localhost" works only with Chromium Fetch

### ISSUE THREAD

**Issue by WolfgangHG** [flawiddsouza/Restfox#94]
I have a local WildFly server (https://www.wildfly.org/downloads/ - requires Java 11), which provides only http urls by default: https://localhost:8080
This fails with Restfox with this error:

```
Error: Request failed
Possible causes for this error:
1) Given request URL is incorrect or invalid
2) The server for the url isn't returning a valid response for the created request
3) The server for the url has an expired or invalid ssl certificate
```

![image](https://github.com/flawiddsouza/Restfox/assets/138049/aae2e16c-fe91-41ba-bef7-10c178afe9ef)

It works when switching to Chromium Fetch.

Would be nice if Restfox would support plain HTTP urls out of the box.

**Comment by flawiddsouza** [comment]
Just to clarify, is it just this server's urls that are failing or do the requests fail for any http url?

**Comment by WolfgangHG** [comment]
You are right - I googled for any http page and found this test site: http://testphp.vulnweb.com/, which opens fine in Restfox. 

Maybe related to port 8080? Or do you have another idea on what to look for?

**Comment by flawiddsouza** [comment]
More I think about this, it seems like the current implementation is not able to reach localhost maybe if listening at 127.0.0.1 or something.

Can you check if your wildfly server is accessible at http://127.0.0.1:8080?

Logically 127.0.0.1 should be equal to locahost. But for some reason it's not. Need to understand why.

I'm trying to reproduce the issue by running the wildfly server on my pc.

**Comment by flawiddsouza** [comment]
Heyo, I've released a new version that should fix this: https://github.com/flawiddsouza/Restfox/releases/tag/v0.5.0. I was able to reproduce this issue locally. Let me know if the issue still persists after the update to v0.5.0.

**Comment by WolfgangHG** [comment]
I can confirm that it works. Many thanks for the great support!
