### ISSUE TITLE
Import from Insomnium

### ISSUE THREAD

**Issue by 7cio** [flawiddsouza/Restfox#95]
Insomnium is a fork of Insomnia. Would be nice if Restfox support importing from Insomnium
https://github.com/ArchGPT/insomnium

**Comment by flawiddsouza** [comment]
Hi @7cio, as importing from Insomnia is already supported:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/0f1848d6-3067-4a2f-ad57-5c1c062eea14)
I assume the export from Insomnium should also work. Unless they've changed the structure of the export. If so, can you please attach a sample export here, so I can implement the required support?

**Comment by 7cio** [comment]
I've just tested and it's not working.
![image](https://github.com/flawiddsouza/Restfox/assets/89747033/8758c2e0-9f40-476e-91f8-f1e19d525dea)

Here is the example.
[Insomnium_2024-03-08.json](https://github.com/flawiddsouza/Restfox/files/14540486/Insomnium_2024-03-08.json)

**Comment by flawiddsouza** [comment]
Thanks for providing that export. That was helpful in finding the issue. I've pushed a fix and it will be included in a next release. Which should be soon.

**Comment by flawiddsouza** [comment]
Hi @7cio. This issue should be fixed as of the latest release: https://github.com/flawiddsouza/Restfox/releases/tag/v0.6.0.
