### ISSUE TITLE
[feature] another way to move a request to a folder beside drag & drop

### ISSUE THREAD

**Issue by vcoris** [flawiddsouza/Restfox#97]
It would be nice to have another way to move a request to a folder beside drag & drop, especially when the list of requests is very long.
I think HTTPie is a good reference.

Maybe having a folder list on the request's properties modal is a good option.
![24_03_12_12_05_2399](https://github.com/flawiddsouza/Restfox/assets/143746244/79205587-a051-4589-993d-b08a66483b49)

**Comment by flawiddsouza** [comment]
Sounds like a good feature to have.
